### ISSUE TITLE
Maven checks randomly fail due to Javadoc errors

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#1017]
The quality gate for Maven leads to random failures of PR checks, see, e.g.: https://github.com/eclipse-platform/eclipse.platform/pull/1014/checks?check_run_id=19609932189

This is the case even though the quality gate has been reduced to only fail on errors: https://github.com/eclipse-platform/eclipse.platform/pull/1007

### Analysis

The logs contain several errors because the optional `javax.*` dependencies cannot be resolved in the Javadoc generation. This is, for example, the case for the `org.eclipse.e4.core.contexts` bundle. These errors will, however, not be reported as Javadoc or Maven errors for some reason. The Maven report for `org.eclipse.e4.core.contexts` does not contain them: https://ci.eclipse.org/platform/job/eclipse.platform/job/master/572/maven-warnings/moduleName.53733659/

Sometimes, however, these errors are reported, see e.g.: https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1014/2/maven-warnings/Error/source.ce60fa94-2a79-4128-a55b-2f2c00681bde/#3357
Then the Maven quality gate does not pass. From what I have seen in the logs, the error seems to be considered if, and only if, it comes right after one of the resolution warnings:
```
17:33:26.600 [INFO] from resources/tests/org.eclipse.core.tests.resources/pom.xml
17:33:26.600 [INFO] ------------------------[ eclipse-test-plugin ]-------------------------
17:33:26.709 [WARNING] Problems resolving provisioning plan.:
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).
Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).
17:33:26.805 [ERROR] MavenReportException: Error while generating Javadoc:
Exit code: 1
/home/jenkins/agent/workspace/eclipse.platform_PR-1014/runtime/bundles/org.eclipse.e4.core.contexts/src/org/eclipse/e4/core/contexts/Active.java:31: error: package javax.inject does not exist
```
Another indicator for this is that the Javadoc generation error is not reported for the plugin in which that error happens [(in this case `org.eclipse.e4.core.contexts`](https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1014/2/maven-warnings/moduleName.53733659/)) but in the one to which the resolution warning belong ([in this case `org.eclipse.core.tests.resources`](https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1014/2/maven-warnings/moduleName.-1217754864/)).

### Expectation

I see two things that could/should be fixed here (excluding the dependency issue discusssed in #969):
1. The log should not contain errors, i.e., the Javadoc errors due to the non-resolved, optional `javax.*` dependency need to be resolved.
2. The warnings should not be treated as errors if there are subsequent log lines containing the word "error". Seems like the plugin parsing the warnings is not completely aware of parallel builds in which subsequent log lines may belong to a completely different module.

While both seems to be issues that should be fixed from my point of view, either should solve the problem of random build failures (even disabling parallel build should so not, but that's not a valid option).

**Comment by HeikoKlare** [comment]
This is related to #782.

**Comment by laeubi** [comment]
> see e.g.: https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1014/2/maven-warnings/Error/source.ce60fa94-2a79-4128-a55b-2f2c00681bde/#3357

**Comment by HeikoKlare** [comment]
Here is a recent error reported for Maven because a Javadoc error was logged right after the dependency warnings:
https://ci.eclipse.org/platform/job/eclipse.platform/view/change-requests/job/PR-1005/2/maven-warnings/Error/source.5c7571b4-5a1f-4a6e-a5df-90f24a8fd66b/#4717

## Relevant Information
Some important infos to be archived here, since the logs will be removed once the PR is merged.

### Overall Build Results

![image](https://github.com/eclipse-platform/eclipse.platform/assets/755472/9c5c135d-0ba1-44ea-be74-08bc48edcdf3)

### Log Extract of Build Result
```
14:31:00.908 [INFO] ------------------------------------------------------------------------
14:31:00.908 [INFO] BUILD SUCCESS
14:31:00.908 [INFO] ------------------------------------------------------------------------
14:31:00.908 [INFO] Total time:  18:35 min (Wall Clock)
14:31:00.908 [INFO] Finished at: 2023-12-15T14:31:00Z
14:31:00.908 [INFO] ------------------------------------------------------------------------
```


### Log Extract for Error

Log for the reported Maven error: 
https://ci.eclipse.org/platform/job/eclipse.platform/view/change-requests/job/PR-1005/2/maven-warnings/Error/source.5c7571b4-5a1f-4a6e-a5df-90f24a8fd66b/#4717

```
14:18:00.819 [INFO] -------< org.eclipse.platform:org.eclipse.core.tests.resources >--------
--
14:18:00.819 [INFO] Building org.eclipse.core.tests.resources 3.11.400-SNAPSHOT [47/112]
14:18:00.819 [INFO] from resources/tests/org.eclipse.core.tests.resources/pom.xml
14:18:00.819 [INFO] ------------------------[ eclipse-test-plugin ]-------------------------
14:18:01.338 [WARNING] Problems resolving provisioning plan.:
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).
Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).
Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).
14:18:01.964 [ERROR] MavenReportException: Error while generating Javadoc:
Exit code: 1
/home/jenkins/agent/workspace/eclipse.platform_PR-1005/runtime/bundles/org.eclipse.e4.core.contexts/src/org/eclipse/e4/core/contexts/Active.java:31: error: package javax.inject does not exist
@javax.inject.Qualifier
^
1 error
Command line was: /opt/tools/java/openjdk/jdk-17/17.0.2+8/bin/javadoc @options @packages
```

### Logged Maven Error

![image](https://github.com/eclipse-platform/eclipse.platform/assets/755472/d3f8af90-6dc3-401e-8d28-7310f260a33b)

![image](https://github.com/eclipse-platform/eclipse.platform/assets/755472/0185ca3f-7963-4e6b-b433-e2561d1a062f)

**Comment by laeubi** [comment]
@HeikoKlare please rebase the build and see if there are still issue present.

**Comment by HeikoKlare** [comment]
Thanks for fixing the javax dependency issue, @laubi!

I have rebased #977 as an example and the log now does not show the errors anymore. There is now a bunch of other Javadoc errors that were "hidden" before, but they can / need to be fixed in the platform code. They are caused by Javadoc references to things not declared in the bundle's manifest, e.g.:
```
/home/jenkins/agent/workspace/eclipse.platform_PR-977/runtime/bundles/org.eclipse.e4.core.di.extensions/src/org/eclipse/e4/core/di/extensions/OSGiBundle.java:23: error: reference not found
 * A method or field of type {@link org.osgi.framework.BundleContext}
 ```

**Comment by HeikoKlare** [comment]
I just saw that it was not sufficient as `javax.annotation` is also used:

```
/home/jenkins/agent/workspace/eclipse.platform_PR-977/runtime/tests/org.eclipse.e4.core.javax.tests/src/org/eclipse/e4/core/internal/tests/contexts/inject/AnnotationsInjectionTest.java:22: error: package javax.annotation does not exist
import javax.annotation.PostConstruct;
```

**Comment by laeubi** [comment]
Not sure if it is useful to have javadoc for test bundles, maybe we should have a switch to disable it that can be used for test-fragments?
Beside that we can add 

```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```

to the additional dependencies.

**Comment by HeikoKlare** [comment]
You are right, it probably makes more sense to disable Javadoc generation for the test bundle. In particular because the test bundle is only a copy for testing backwards compatibility to javax.
