### ISSUE TITLE
Expand all the packages of Java project in Eclipse IDE in single click

### ISSUE THREAD

**Issue by sanketcs30** [eclipse-platform/eclipse.platform#1060]
Hi @vogella @iloveeclipse in eclipse in order to **collapse all the opened packages of the project** there is minus symbol in the IDE , but **how can one expand all the packages of the projects in single click**
I have **tried default shortcut key ctrl + shift + Numpad * to expand** all the packages of the project , but it's not working , is there any way to perform this expand packages operation in single click
Thanks

![Eclipse Expand](https://github.com/eclipse-platform/eclipse.platform/assets/150379281/b8e24c3a-d221-4314-a5e3-7bc0d09a533b)

**Comment by Bananeweizen** [comment]
In any tree the **numpad keys** can be used: + to expand, - to collapse, * to expand recursive. Be careful with recursive, if you try that on a project top level node, the IDE might be blocked for minutes, trying to expand millions of nodes.

**Comment by merks** [comment]
It is possible to implement expand all in a way that limits the time spent and expands where attention is focused:

https://github.com/eclipse-emf/org.eclipse.emf/blob/5eae1280091bfa2fb5971dac7032e995ab9939e6/plugins/org.eclipse.emf.edit.ui/src/org/eclipse/emf/edit/ui/action/ExpandAllAction.java#L83-L97

**Comment by Bananeweizen** [comment]
@merks Nice thing, Ed. But that still wouldn't prevent the numpad multiply to cause such issues, unless we could move it into SWT or Jface for the very general expand all, right? As of now, one would have to find the dangerous expand operations by bug reports, one by one, and then apply your solution to the key combination instead. Or do you have something more generic for mapping _any_ expand recursive this way?
(And yes, I had to kill my IDE after I tried expand recursive on a real world project node)

**Comment by merks** [comment]
It's just an FYI.  I did not know about the numpad * thing!   Of course not providing a functional/smart expand all tool button also will not prevent the numpad * danger.   😛   Use at own risk...

**Comment by jukzi** [comment]
> In any tree the **numpad keys** can be used: + to expand, - to collapse, * to expand recursive. Be careful with recursive, if you try that on a project top level node, the IDE might be blocked for minutes, trying to expand millions of nodes.

BTW: that can be interrupted with ESC

**Comment by sanketcs30** [comment]
Thanks @Bananeweizen @merks @jukzi , I tried this but it's taking time and stops IDE for some time , I thought there is some button or option like **"Expand all"** which might be available in the earlier versions of Eclipse IDE
