### ISSUE TITLE
Failing PreferencesServiceTest#testLookupOrder()

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#1073]
The test case `org.eclipse.core.tests.internal.preferences.PreferencesServiceTest#testLookupOrder()` constantly fails, e.g.: https://github.com/eclipse-platform/eclipse.platform/actions/runs/7406826268/job/20152527917
```
unexpected exception type thrown; expected:<java.lang.IllegalArgumentException> but was:<java.lang.NullPointerException>
java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.IllegalArgumentException> but was:<java.lang.NullPointerException>
	at org.junit.Assert.assertThrows(Assert.java:1020)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at org.eclipse.core.tests.internal.preferences.PreferencesServiceTest.testLookupOrder(PreferencesServiceTest.java:232)
```

The reason is a regression in Equinox: https://github.com/eclipse-equinox/equinox/issues/464

**Comment by iloveeclipse** [comment]
Fixed via https://github.com/eclipse-equinox/equinox/pull/465
