### ISSUE TITLE
random failing org.eclipse.core.tests.resources.HiddenResourceTest testRefreshLocal

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#108]
Verifying delta for / Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/.project Missing expected change Actual kind: <CHANGED> Actual change flags: <ENCODING> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/file.txt Missing expected change Actual kind: <CHANGED> Actual change flags: <ENCODING> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt Conflicting change Expected change flags: <CONTENT> actual change flags: <ENCODING> Verifying delta for / Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt Missing expected change Actual kind: <CHANGED> Actual change flags: <CONTENT>

junit.framework.AssertionFailedError: Verifying delta for /
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/.project
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <ENCODING>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/file.txt
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <ENCODING>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt
Conflicting change
Expected change flags: <CONTENT> actual change flags: <ENCODING>
Verifying delta for /
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <CONTENT>

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.core.tests.resources.HiddenResourceTest.testRefreshLocal(HiddenResourceTest.java:37)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by HeikoKlare** [comment]
Closed as failure has not occurred recently.
