### ISSUE TITLE
Update guideline for adding full issue urls in commits

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#11]
I propose to slightly change [contributing guidelines](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) and to recommend to add a **full url** to the commit messages, like this:
```
test_traverseCheckButton fails on Linux

Disabling new test on Linux for now.

Fixes issue
https://github.com/eclipse-platform/eclipse.platform.swt/issues/27
```

See 
https://github.com/eclipse-platform/eclipse.platform.swt/commit/ca1dcb011a7386fba5ad3ca72dfcd361432b09f2

Please note, the github UI strips the actual url from the commit text, so we see 

```
test_traverseCheckButton fails on Linux
Disabling new test on Linux for now.

Fixes issue
#27
```

The reason is that it is much easier to navigate to the right bug from git log / egit UI if you have full url shown in the commit message.

**Comment by akurtakov** [comment]
@iloveeclipse Would you please provide PR for that change?

**Comment by HeikoKlare** [comment]
This has been fixed via eclipse-platform/.github#125
