### ISSUE TITLE
slow BuildManager DeltaDataTree computations

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#111]
I sampled my eclipse while i was programming in a big workspace with many projects and see half the time during autobuild is spend below org.eclipse.core.internal.events.BuildManager$DeltaCache.computeIfAbsent(). That feels wrong: the actual building should take longer then computing what to build.
![image](https://user-images.githubusercontent.com/51790620/184820766-b32914e9-bb88-4ec3-bfd6-1c16cefd0cd9.png)

Hotspots are in AbstractDataTreeNode, DeltaDataTree:
![image](https://user-images.githubusercontent.com/51790620/184822438-3c4aa88d-a326-499b-b00a-277905113e20.png)
example calltree:
![image](https://user-images.githubusercontent.com/51790620/184822971-b42f35b6-6cee-4a3c-9267-34ec59bf29c4.png)
![image](https://user-images.githubusercontent.com/51790620/184823178-519ee927-f60a-4d32-852b-70852b0a54da.png)

This is just a reminder that there may be possible optimizations: To compute if a single project has a delta it is wasted time to compute the delta for other projects too. Also to compute if a projects needsBuild() it could exit early as soon as any delta is found instead of actually computing the whole delta.
![image](https://user-images.githubusercontent.com/51790620/184822563-05a3f06d-f8f0-4944-9f19-d2f4d8ff796d.png)

**Comment by vogella** [comment]
Moved to platform, as resources has been merged with eclipse.platform repo.

**Comment by jukzi** [comment]
> Moved to platform, as resources has been merged with eclipse.platform repo.

Please disable issues and pull requests in the /settings of the old repos.

**Comment by vogella** [comment]
> > Moved to platform, as resources has been merged with eclipse.platform repo.
> 
> Please disable issues and pull requests in the /settings of the old repos.

The repo may still be used for maintenance work (IIRC some IBM committers do this sometimes) so issues and pr needs to stay activated.
