### ISSUE TITLE
Compare Tool misalign difference indicators if custom line spacing is used

### ISSUE THREAD

**Issue by xmichael91** [eclipse-platform/eclipse.platform#1197]
## Steps to reproduce

* Go to Preferences, and set some value for General->Editors->Text Editors->Line Spacing field (e.g. 25).
* Open Compare Tool for two different files/revisions (e.g. select two different files in your workspace and start the tool).
* Observe misaligned lines as on the attached screenshot.

![screenshot](https://github.com/eclipse-platform/eclipse.platform/assets/51908948/d3197590-994b-4a4d-9675-5223b8b8c246)

## Tested under this environment:
Eclipse IDE for RCP and RAP Developers (includes Incubating components)
Version: 2023-12 (4.30.0)
Build id: 20231201-2043
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.10+7
Java version: 17.0.10

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by DenisUngemach** [comment]
Hello, 

in the TextMergeViewer in line 4530 the line height will be used directly, this seems to cause this error:

int lineHeight = tp.getSourceViewer().getTextWidget().getLineHeight();

The calculation of the line height is only the size of the textfont, and not the height with additional attributes like the line spacing.

I will check how to fix this.

Best regards,
Denis

**Comment by DenisUngemach** [comment]
Hi, 

this commit fixes the problem: https://github.com/DenisUngemach/eclipse.platform
This is not perfect, because the real calculation of line heights should be inside the text widget and the renderer not outside in the compare tool.

**Comment by iloveeclipse** [comment]
@DenisUngemach : I assume you mean this commit: https://github.com/DenisUngemach/eclipse.platform/commit/b4343794a49f718bcc1235fc3c1599527dc6354d (your link above doesn't work).

Could you please open a PR so the change could be reviewed properly?

**Comment by DenisUngemach** [comment]
> Thanks Denis!

You're welcome. I will check the other issue you mentioned.
