### ISSUE TITLE
Texts not externalised

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform#1236]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

Have a look at https://github.com/eclipse-platform/eclipse.platform/blob/a17ae73905f80cbd162cb17f96257c62fd63d2ed/team/bundles/org.eclipse.compare/compare/org/eclipse/compare/contentmergeviewer/TextMergeViewer.java#L5424C1-L5425C109

You see that the texts are not externalised and therefore cannot be translated.
This was overlooked in https://github.com/eclipse-platform/eclipse.platform/pull/731

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by lathapatil** [comment]
> @lathapatil: Can you provide a fix for this?

Yes. Can I create the those strings in ICompareUIConstants.java file ?

**Comment by BeckerWdf** [comment]
> > @lathapatil: Can you provide a fix for this?
> 
> Yes. Can I create those strings in ICompareUIConstants.java file ?

No. Pls. have a look at https://github.com/eclipse-platform/eclipse.platform/blob/master/team/bundles/org.eclipse.compare/compare/org/eclipse/compare/internal/CompareMessages.java#L20
