### ISSUE TITLE
 Compare with left and right scrollbars sliding asynchronously to enhance modification proposals

### ISSUE THREAD

**Issue by lyh061619** [eclipse-platform/eclipse.platform#1238]
When comparing two files using compare with, scrolling the scroll bar left and right with the mouse will not synchronize. It is not convenient to compare files in practice. It is recommended to adjust to synchronous scrolling to improve work efficiency

![20240306111455](https://github.com/eclipse-platform/eclipse.platform/assets/15118571/b999478d-dff0-45c1-b9e1-7e9addd52d4c)

**Comment by jukzi** [comment]
That would fit the synchronized vertical scrolling. If you want that feature please provide a PR and make sure there is a option to disable it in the context menu, as it may not be wanted in all cases.

**Comment by lyh061619** [comment]
> That would fit the synchronized vertical scrolling. If you want that feature please provide a PR and make sure there is a option to disable it in the context menu, as it may not be wanted in all cases.
My suggestion is to keep the direction of the left and right window scrollbars synchronized when sliding left and right. This is more practical in actual file comparison work, but the current problem is that when I use the mouse to slide the scrollbars left and right, they will not synchronize

**Comment by lyh061619** [comment]
The problem has been resolved
