### ISSUE TITLE
LaunchConfigurationTabGroupViewerTest fails on all platforms

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1239]
I20240306-1800
for example https://download.eclipse.org/eclipse/downloads/drops4/I20240306-1800/testresults/html/org.eclipse.debug.tests_ep432I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
```
java.lang.AssertionError:
Expecting actual:org.eclipse.debug.tests.ui.SpyTab$SpyTabA@20bc4c09to match 'is activated' predicate.
at org.eclipse.debug.tests.ui.LaunchConfigurationTabGroupViewerTest.testFirstTabIsActivatedByDefault(LaunchConfigurationTabGroupViewerTest.java:86)at java.base/java.lang.reflect.Method.invoke(Method.java:580)

```

may relate to https://github.com/eclipse-platform/eclipse.platform/issues/1075

**Comment by iloveeclipse** [comment]
> may relate to #1075

No, it is a regression from https://github.com/eclipse-platform/eclipse.platform.swt/pull/1044.
Reverting SWT change fixes the test.

**Comment by iloveeclipse** [comment]
Fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20240307-1800/testResults.php
