### ISSUE TITLE
Circular dependency error when using JPMS

### ISSUE THREAD

**Issue by newmangreen** [eclipse-platform/eclipse.platform#1243]
Hi, 
We are on a project to migrate a big Java application containing multiple modules. 
We decided to use Java module system in compile-time only but when using Eclipse it is not possible to use circular dependency
in module-info.java. To fix this dependency problem in our application is "impossible".

Let's say we have 2 modules depends each other; X -> Y and Y -> X
During defining this relationship in module-info.java, 
Eclipse gives this error "Cycle exists in module dependencies, Module X requires itself via Y"

Yes, circular dependency is a bad thing but before JPMS(Java 9) we can bypass this control by changing this setting to "Warning". Preferences>Java>Compiler>Build Path Problems>Circular dependencies = Error -> Warning

What I suggest is, same setting or a new setting should provide this bypass as before. So, what I expect is if it is set to "Warning", 
then compiler should not complain about circular dependency in module-info as well.

Thank you.

**Comment by merks** [comment]
Please use ask for this feature here:

https://github.com/eclipse-jdt/eclipse.jdt.core/issues

I cannot transfer the issue to another GitHub organization.

**Comment by newmangreen** [comment]
I read submission guidelines(JDT wasn't there?) but missed repository, ok will do it.
