### ISSUE TITLE
Not able to install Java 22 support for Eclipse 2024-03 (4.31)

### ISSUE THREAD

**Issue by anbusampath** [eclipse-platform/eclipse.platform#1259]
## Steps to reproduce

Installed new Eclipse 4.31
I tried to install Java 22 support for Eclipse 2024-03 (4.31) from marketplace, but installation fails

<img width="591" alt="image" src="https://github.com/eclipse-platform/eclipse.platform/assets/1268973/82189a97-5dd3-41cd-8dbc-ff4cefc6a749">
<img width="529" alt="image" src="https://github.com/eclipse-platform/eclipse.platform/assets/1268973/efea6651-b100-4c74-b951-8a652883f9cf">
<img width="601" alt="image" src="https://github.com/eclipse-platform/eclipse.platform/assets/1268973/2626e2ed-733f-4559-83c2-adf22cd5a5e7">

## Tested under this environment:
* OS & version: MacOS 14.4
* Eclipse IDE/Platform version Eclipse Platform

Version: 4.31.0.v20240229-1022
Build id: I20240229-0520

**Comment by merks** [comment]
It worked for me (on Windows) when I have this installed:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/d26ac40b-c4b3-4a07-9e9d-c30ccf02e642)

Could you please make a screen capture of the Help -> About Dialog of your installation so we can be sure exactly which version of which product you have installed?

**Comment by anbusampath** [comment]
I see there is build number mismatch. let me download again and try.
