### ISSUE TITLE
Windows Defender exclusion check running on each start-up

### ISSUE THREAD

**Issue by kriegaex** [eclipse-platform/eclipse.platform#1264]
On Eclipse 2024-03 Java IDE, the Windows Defender exclusion check runs again and again, no matter how often I permit it to add an exception with admin privileges. If it is relevant, I have manually added Eclipse-related exclusions years ago, before this feature even existed. Anyway, the checker should add its entry once and only once, report a result to the user and then be silent henceforth, unless the next Eclipse installation ends up in another path.

Please feel free to advise me to attach whichever (parts of) logs you wish to see from my workstations. I will be happy to comply and help you to debug this to the best of my abilities. In the workspace log (error log), I see nothing when running the check from the settings page.

**Comment by Bananeweizen** [comment]
I'm not sure how exactly that mechanism works, but I would assume it will be triggered again if that powershell script fails. therefore it might be useful to copy the script from Preferences>Startup and shutdown, execute it manually in a terminal and check for errors in the output.

**Comment by merks** [comment]
If the installation folder name contains a space, this is a known problem:

https://github.com/eclipse-platform/eclipse.platform.ui/issues/1757

**Comment by kriegaex** [comment]
@merks, is there any way to consume a related update in Eclipse IDE 2024-03?

**Comment by merks** [comment]
Unfortunately not until the first milestone, then updates will also be available here:

https://download.eclipse.org/releases/milestone
https://download.eclipse.org/releases/2024-06

according to this schedule:

https://github.com/eclipse-simrel/.github/blob/main/wiki/SimRel/2024-06.md

**Comment by sschneider** [comment]
Can someone point me to the config file to directly set the exclusion flag, please?

**Comment by HannesWell** [comment]
@kriegaex is this still an issue with Eclipse 2024-06 or this this already fixed as Ed anticipated?

**Comment by kriegaex** [comment]
@HannesWell, the IDE does not ask me anymore, which looks good. A related question: If I click "Run exclusion check now", I always see this:

![image](https://github.com/user-attachments/assets/25b8fa0a-6d8e-41f7-8845-33181b613ae6)

The dialogue does not indicate the current state, it always looks as if it is runing for the first time. Is this intended?

**Comment by HannesWell** [comment]
> The dialogue does not indicate the current state, it always looks as if it is runing for the first time. Is this intended?

Yes that's intended. The reason is that Eclipse does not know the real state of the exclusion because one can only query that with Administrator privileges. And since we only want to ask for these privileges if really necessary (I would find it suspicious if an IDE always needs them) it is only remembered what Eclipse tried to do and assumes has worked (i.e. there was not Exception or alike).
The `Run exclusion check now` button in the preferences is therefore intended to start the procedure again for cases where the exclusion was changed externally or failed in unknown ways.

**Comment by kriegaex** [comment]
> Eclipse does not know the real state of the exclusion because one can only query that with Administrator privileges

So, how does Eclipse determine whether to show the warning or not? Either I am overlooking something obvious, or your statement is incorrect. Please explain.

**Comment by HannesWell** [comment]
> > Eclipse does not know the real state of the exclusion because one can only query that with Administrator privileges
> 
> So, how does Eclipse determine whether to show the warning or not?

It simply just remembers if the dialog has been closed with a successfully executed discussion. I.e. if either the user deiced to keep the Defender running as it is or has decided to exclude eclipse and the exclusion ran without errors.

**Comment by kriegaex** [comment]
That is a surprising approach, but I can understand why it was implemented this way after you explained it to me. Thanks for that.
