### ISSUE TITLE
Cannot open my workspaces in 2024-03

### ISSUE THREAD

**Issue by ekekakos** [eclipse-platform/eclipse.platform#1279]
Hello. I upgrade my eclipse in the version of 2024-03 and transforming my workspaces to the new version I cannot open it.
It says that there is an error see .LOG file which I included.
[.log](https://github.com/eclipse-platform/eclipse.platform/files/14821652/default.log)
Please help me the soonest possible as I cannot work.

Thanks in advance
Elias Kekakos

**Comment by laeubi** [comment]
Please try to start eclipse with the `-clean` option

**Comment by ekekakos** [comment]
I did it but the same problem 
[.log](https://github.com/eclipse-platform/eclipse.platform/files/14822492/default.log)
![eclipse 2024-03 error](https://github.com/eclipse-platform/eclipse.platform/assets/7590587/850da536-a4ac-4d0f-9182-233e8f371d4a)

**Comment by merks** [comment]
Looking at the stack traces, it seems to me something (SWT) did not update correctly:
```
java.lang.NoSuchMethodError: 'org.eclipse.swt.graphics.ImageData org.eclipse.swt.internal.DPIUtil.validateAndGetImageDataAtZoom(org.eclipse.swt.graphics.ImageDataProvider, int, boolean[])'
	at org.eclipse.swt.graphics.Image._createDisabled(Image.java:458)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:245)
	at org.eclipse.jface.resource.DerivedImageDescriptor.internalCreateImage(DerivedImageDescriptor.java:83)
	at org.eclipse.jface.resource.DerivedImageDescriptor.createResource(DerivedImageDescriptor.java:51)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
```
The path of least resistance would be to install a new IDE from scratch...

You might try `eclipse.exe -data <clean-new-workspace>`, where `<clean-new-workspace>` is the name of some file that will be the empty new workspace.  I doubt that will start, but it will confirm that you installation simply doesn't start regardless of which workspace is used.

**Comment by ekekakos** [comment]
Finally nothing resolved my problem. So I proceed with installing the latest version from scratch. The bad think is that I have to do all setups again.

**Comment by merks** [comment]
@ekekakos 

Yes, I sympathize.  This is the reason why I basically never create installations manually:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring

So I create p2 tasks that do everything:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring#How_to_install_Eclipse_plugins_using_the_P2_Director_and_Repository_Explorer

Then it's possible to set up an entire environment automatically, e.g.,

**Comment by aztechowski** [comment]
Does it have something common with deprecation of Equinox Bundles and their usage in the installed extensions? Btw. the same issue is reported here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=583025
