### ISSUE TITLE
Can't install exlipse on mac with older system Catalina 10.15.7

### ISSUE THREAD

**Issue by fmatuszewski** [eclipse-platform/eclipse.platform#1324]
I have an older machine which I use for development purposes but I can't Install mac os update because it is not supported.
I assume eclipse is a java application so I should be able to run it from jar file. 
Where can I find jar build of the IDE.

**Comment by merks** [comment]
SWT is tightly integrated with native OS widgets so you'll need to find an older download that works on the older mac.  

You can find older downloads here. 

https://www.eclipse.org/downloads/packages/release

**Comment by jukzi** [comment]
closing because answer is given.

**Comment by Letterus** [comment]
The last version working on Catalina 10.15 (without any hacks) is 2023-12.
