### ISSUE TITLE
.project and .settings folders are not visible

### ISSUE THREAD

**Issue by uqpik** [eclipse-platform/eclipse.platform#1328]
I switched from Eclipse 2012-12 to 2024-03. In 2024-03, the file .project and folder .settings is no longer visible.
In addition, they are excluded from search too. 

Also, if changes are made in the project properties (that may cause modifications in one of the mentioned resources). They are not recognized by EGit until Eclipse is restarted.

Steps to reproduce:
- Create a new  Project
- Within the Project Explorer - Filter and Customizations uncheck .* resources
  -> .project is now visible -> ok

- restart Eclipse
  -> .project is no longer visible -> not ok

**Comment by merks** [comment]
Yes this works for me too.  I do this in many of my workspaces.

**Comment by iloveeclipse** [comment]
So let's close as not reproducible.

**Comment by uqpik** [comment]
Sorry, the files are hidden by the DBeaver Plugin.
