### ISSUE TITLE
JobGroupTest.testGetActiveJobs() fails in IDE

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#134]
org.eclipse.core.tests.runtime.jobs.JobGroupTest.testGetActiveJobs() fails when run as JUnit Plug-Test from within the IDE,
it passes when run as plain JUnit Test.
There is already comments & code that try to avoid that situation but it does not work.
![image](https://user-images.githubusercontent.com/51790620/187605381-a18efb7a-d2d0-4bb4-9f57-cbb0e8e2411b.png)

**Comment by laeubi** [comment]
> it passes when run as plain JUnit Test.

Why is it not sufficient to run it as a plain JUnit Test then?

**Comment by jukzi** [comment]
it is sufficient, but it's frustrating if you do not know how to run which test.

**Comment by laeubi** [comment]
Yes this is a general problem, but it seems no one mind enough to work on a solution yet, so I think only focus on a single test, or make tests run in both context (which is simply a waste of time as a plugin test has much higher startup costs) might not improve much here.

I think a usual techniqe today would be to simply annotate tests that require to be a plugintest, that way even one can hide the "plain" JUnittest option for those.

**Comment by jukzi** [comment]
It's the only test that fails from org.eclipse.core.tests.runtime.jobs.AllTests ... so i created this ticket to document that. 

> I think a usual techniqe today would be to simply annotate tests that require to be a plugintest, that way even one can hide the "plain" JUnittest option for those.

sounds great (but it's the other way around). what is the annotation for that?

**Comment by mickaelistria** [comment]
It seems to be working within Tycho surefire and also on I-Build tests (where a headless Eclipse is running). Have you tried running it without the workbench, selecting the "No application" application in the Launch Config?

**Comment by jukzi** [comment]
> selecting the "No application" application in the Launch Config

then it passes
