### ISSUE TITLE
Launch configuration is being overwritten when selected in the Run Configuration dialog

### ISSUE THREAD

**Issue by aptmac** [eclipse-platform/eclipse.platform#1357]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* For this specific use case: Import JDK Mission Control and it's development files (missioncontrol.core, missioncontrol.application, target-definitions, and launchers)
* Edit a launch configuration file in the Eclipse IDE
* Select the launcher in the run configuration dialog
* The launch configuration will be overwritten

I expected: to run the application using the launcher I was editting

But got: the launcher was overwritten

I'm trying to update the versions for some dependencies in a launch configuration, but whenever I try to actually run it the file is overwritten when selected in the run configuration dialog. I've also tried editing the launcher first and then re-importing it, but it doesn't make a difference.

Edit: Also forgot to mention, in the (few) times where the launcher isn't completely overwritten, the dependency versions are updated automatically somehow. For example, I'm listing a bunch of jetty dependencies at version 10.0.18, and then without any intervention the launchers will have some listed at 10.0.18, and then some at the newer 12.0.3, and it causes issues when trying to run.

Gif: 
![eclipse-launch-overwrite](https://github.com/eclipse-platform/eclipse.platform/assets/10425301/4608747b-ff3f-4134-8508-ccc2beeb8516)

## Tested under this environment:
* OS & version: Fedora 40
* Eclipse IDE/Platform version (as shown in *Help > About*): 2023-12

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by Bananeweizen** [comment]
This is not a bug. The model behind launch configurations develops over time. Therefore editing an older launch config in a newer version of Eclipse will lead to adding new properties and removing no longer supported ones. Also there has been one version of eclipse some years ago where the sorting an indentation of the XML serialization changed completely, your files might be from before that time. The content of the attributes however, remains the same (as much as the current properties are still supported).
Independent of that, the versions of target platform plugins in PDE based launch configurations are changed to the current ones in the currently loaded target platform, as you cannot start a bundle in a version that doesn't exist. So if you want to avoid plugin version number changes in PDE launch configs, _first_ load the respective target platform, _then_ edit the launch configs.

If you want to avoid the launch configs being changed, launch them without using this dialog. There is separate "launch configs" view that can launch all existing launch configurations. Also you can mark launch configurations as favorites, to run them from the Run/Debug menus. And you can use the context menu on stored launch configs.

**Comment by aptmac** [comment]
Thanks for the reply, I didn't realize that this was a feature but I can see how it could be useful now.

> This is not a bug. The model behind launch configurations develops over time. Therefore editing an older launch config in a newer version of Eclipse will lead to adding new properties and removing no longer supported ones.

While this is neat, I wonder if it's also adding to my editing issue, maybe a unique use case here. Specifically, in Eclipse 2023-12 and onwards there are two versions of most jetty plugins, in this case it's versions 10.0.18 and 12.0.3.So in my launcher it looks like the dependency numbers were being bumped up to 12.0.3, but for example jetty.servlet doesn't have it's 12.0.3 plugin in the 2023-12 target platform, only 10.0.18.

**Comment by aptmac** [comment]
Thanks for the reply, I can see how this would be a neat feature, and it's probably been working in the background for me before without me noticing it.

> This is not a bug. The model behind launch configurations develops over time. Therefore editing an older launch config in a newer version of Eclipse will lead to adding new properties and removing no longer supported ones.

While this is neat, I think this was the cause of my recent issues, maybe a unique use case here. Specifically, in Eclipse 2023-12 and onwards there are two versions of _many_ jetty plugins, in this case it's versions 10.0.18 and 12.0.3.

Originally in our launcher we had older dependency versions listed, and it does indeed look like these get bumped to the newer versions. What I find a bit confusing is that some of them get auto updated to version 10.0.18, and some to 12.0.3. Slightly problematic is that jetty.servlet only has the 10.0.18 version in the target-platform, so there seems to be a version incompatibility sometimes.
