### ISSUE TITLE
Improve File delete performance

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1461]
Currently Project/Clean... takes much time to only delete the output. Hopefully that can be improved - somehow

![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/c0deaf84-7f5b-4eba-bf0a-eba2884ca7b6)

**Comment by HannesWell** [comment]
I wonder why RemoveDirectory is called if the element to be deleted is actually a file?

In general if the JDK implementation is too generic and therefore too slow we could consider adding a native (JNA, later FFM based) implementation by adding a `delete()` method to the NativeHandler? Maybe we can avoid some of the native calls done in nio.

**Comment by jukzi** [comment]
i have made delete parallel and don't plan further improvements.
