### ISSUE TITLE
broken XML comment in new and noteworthy

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/eclipse.platform#1482]
![grafik](https://github.com/user-attachments/assets/dab49017-6225-41ed-b910-e7316970938d)
see https://eclipse.dev/eclipse/news/4.32/pde.php

I can't map that to the source files of the git repository, so I'm a bit confused. Is there some additional processing of the files?

**Comment by merks** [comment]
That's here:

https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.32/pde.php

He actual content it wraps is

https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.32/pde.html

**Comment by tomaswolf** [comment]
XML comments don't nest. https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/ec1082f0ededd6e37ac6699b9d4ce2d37b944724/news/4.32/pde.html#L87
