### ISSUE TITLE
Attribute transfer in FileStore can lead to issues when copying file contents into another FileStore

### ISSUE THREAD

**Issue by Michael5601** [eclipse-platform/eclipse.platform#1524]
The commit found at https://github.com/eclipse-platform/eclipse.platform/pull/1475 introduced a change in FileStore's behavior, specifically affecting how file attributes are transferred during file copying operations.

Previously, the OutputStream was closed before transferring file attributes. However, the refactoring has altered this sequence, allowing file attributes to be transferred before the OutputStream is closed. As a result, when copying a file, the FileStore may only create the file after closing the OutputStream. This means that, under the new behavior, there is a risk that file attributes could be transferred to a file that does not yet exist.

A PR to fix this is provided in https://github.com/eclipse-platform/eclipse.platform/pull/1525.

**Comment by jukzi** [comment]
@HannesWell please take a look.

**Comment by HannesWell** [comment]
Thanks a lot @Michael5601 for this report and the associated fi in #1525. Nice work.
