### ISSUE TITLE
Navigate > Previous Edit Location thwarted by cloned editor

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-platform/eclipse.platform#1526]
I just recently found this issue, so I can not tell how old it really is.
From the moment you clone an editor to work on two positions in the same file, ^Q takes you to the head
of the method or block were you already are. Obviously the other, inactive, editor on the same file confuses
the positioning algorithm.

OS = MacOS 11.7.10 (BigSur);
Maybe this is a MacOS (INTEL) problem as the definition of CTRL is slightly different from MSWindos.
Eclipse version 4.32

**Comment by jukzi** [comment]
this ticket refers to:
![image](https://github.com/user-attachments/assets/0e335b0f-813e-4d38-ac67-274c1948d743)
![image](https://github.com/user-attachments/assets/f3ed59fe-fb35-4bc0-a87e-95b2b4e19379)

please give concrete steps how to reproduce - what happens and what is expected.

**Comment by merks** [comment]
I assume he means using Window -> Editor -> Clone you can make a second editor editing exactly the same file.

From what I understand of the history mechanism it only keeps track of the editor input and more recently the editor ID to track each editor's locations.  So two editors with the same editor input and the same ID will not be seen as two editors by the history mechanism.

So open any editor, clone it, and then click back and forth between the two.  You'll see there is only ever one history item for the editor:

![image](https://github.com/user-attachments/assets/036a4676-ba4b-48a2-a3e3-feecd0456805)

**Comment by Sciuriware** [comment]
@jukzi Sorry for being not clear.
;JOOP!
