### ISSUE TITLE
Java > Code Style > Clean Up > Java Features > Java 15: text block example misses \n

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform#1528]
This example snippet can't
```java
String buf = "" +
    "public class A {" +
    "    public void foo() {" +
    "    }" + 
    "}";
```
be converted to a text block, because it produces a single-line string.
<img width="687" alt="2024-08-26 15_36_28-Profile 'Eclipse  built-in '" src="https://github.com/user-attachments/assets/5b92b88f-08a0-48f1-91f8-75325baf9566">

**Comment by jukzi** [comment]
for java features please recreate a issue at https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/new
closing as not platform
