### ISSUE TITLE
Add "Enable All" to context menu of Breakpoints view

### ISSUE THREAD

**Issue by SougandhS** [eclipse-platform/eclipse.platform#1532]
The Breakpoints view has a "Disable All" entry in its context menu, which is very convenient when working with a lot of breakpoints. But its missing an "Enable All" entry:
![image](https://github.com/user-attachments/assets/95a00209-b0d8-4870-b0ed-7502ff68853f)

Referring -https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/198

**Comment by SougandhS** [comment]
@MohananRahul Could you please assign this to me.

**Comment by jukzi** [comment]
note that you can already enable all using multiselection (Strg+A) in Breakpoints view + "enable":
![image](https://github.com/user-attachments/assets/68d48310-cfd0-49ba-859a-83143908f64e)
