### ISSUE TITLE
Failing TocLinkChecker.testPdeUserGenerate

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1541]
reproducible and fails all builds, see for example
https://download.eclipse.org/eclipse/downloads/drops4/I20240904-1800/testresults/html/org.eclipse.ua.tests.doc_ep434I-unit-win32-java17_win32.win32.x86_64_17.html

`
Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/overview-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/api/tools/annotations/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/build/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/build/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/plugin/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/project/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/core/target/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/launching/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/launcher/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/target/package-summary.html Invalid link in "/org.eclipse.pde.doc.user/topics_Reference.xml": reference/api/org/eclipse/pde/ui/templates/package-summary.html
`
similar error happend before:
https://github.com/eclipse-platform/eclipse.platform/issues/668

**Comment by iloveeclipse** [comment]
Funny, just reported same for PDE: https://github.com/eclipse-platform/eclipse.platform/issues/1541

**Comment by jukzi** [comment]
Fools rarely disagree ;-)

**Comment by HannesWell** [comment]
> Funny, just reported same for PDE: [eclipse-pde/eclipse.pde#1392](https://github.com/eclipse-pde/eclipse.pde/issues/1392)

This has been fixed in the meantime.
