### ISSUE TITLE
3 PlatformURLSessionTest fails since I20240920-1800 on all platforms

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#1564]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240920-1800/testresults/html/org.eclipse.core.tests.runtime_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Most likely side effect of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2369.

Also we have ~100 osgi test errors, see https://download.eclipse.org/eclipse/downloads/drops4/I20240923-0040/testresults/html/org.eclipse.osgi.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Common thing seem to be that tests rely on SessionTestExtension / SessionTestSuite / `"org.eclipse.pde.junit.runtime.coretestapplication"`.

```
Process returned non-zero code: 13 Command: [ eclipseArguments: {data=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/tmp/workspace, os=linux, test=org.eclipse.core.tests.internal.runtime.PlatformURLSessionTest:test0FirstSession, testpluginname=org.eclipse.core.tests.runtime, version=4, testloaderclass=org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader, application=org.eclipse.pde.junit.runtime.coretestapplication, install=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/workarea/I20240920-1800/eclipse-testing/test-eclipse/eclipse/, port=41739, vm=/opt/tools/java/openjdk/jdk-17/17.0.2+8/bin/java, arch=x86_64, ws=gtk, loaderpluginname=org.eclipse.core.tests.harness, nl=en_US} vmArguments: {} systemProperties: {eclipse.consoleLog=true, osgi.configuration.area.readOnly=false, osgi.configuration.area=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/tmp/eclipse_session_configuration11577756807711097226, org.eclipse.core.tests.session.isRemoteExecution=true, org.eclipse.update.reconcile=false} ]

org.eclipse.core.runtime.CoreException: Process returned non-zero code: 13
Command: [
eclipseArguments: {data=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/tmp/workspace, os=linux, test=org.eclipse.core.tests.internal.runtime.PlatformURLSessionTest:test0FirstSession, testpluginname=org.eclipse.core.tests.runtime, version=4, testloaderclass=org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader, application=org.eclipse.pde.junit.runtime.coretestapplication, install=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/workarea/I20240920-1800/eclipse-testing/test-eclipse/eclipse/, port=41739, vm=/opt/tools/java/openjdk/jdk-17/17.0.2+8/bin/java, arch=x86_64, ws=gtk, loaderpluginname=org.eclipse.core.tests.harness, nl=en_US}
vmArguments: {}
systemProperties: {eclipse.consoleLog=true, osgi.configuration.area.readOnly=false, osgi.configuration.area=/home/jenkins/agent/workspace/AutomatedTests/ep434I-unit-cen64-gtk3-java17/tmp/eclipse_session_configuration11577756807711097226, org.eclipse.core.tests.session.isRemoteExecution=true, org.eclipse.update.reconcile=false}
]
at org.eclipse.core.tests.harness.session.RemoteTestExecutor.executeRemotely(RemoteTestExecutor.java:66)
at org.eclipse.core.tests.harness.session.SessionTestExtensionHost.interceptTestMethod(SessionTestExtensionHost.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by iloveeclipse** [comment]
> Can't we remove the reexport of `org.eclipse.test` from `org.eclipse.performance.test`?

I can confirm this will fix PlatformURLSessionTest and 100 osgi test fails.

However, there are dependencies in various tests across SDK to  `org.eclipse.test`  that has to be fixed first.

What I see in my workspace are these:
* org.eclipse.e4.ui.tests
* org.eclipse.jface.text.tests
* org.eclipse.jdt.debug.tests
* org.eclipse.jdt.core.tests.builder
* org.eclipse.jdt.core.tests.compiler
* org.eclipse.jdt.core.tests.model

Should be doable to fix the dependencies by adding `org.eclipse.test` to the bundle manifests above

**Comment by iloveeclipse** [comment]
> Should be doable to fix the dependencies by adding `org.eclipse.test` to the bundle manifests above

@akurtakov : could you please look at that tomorrow, I have to finish my work day now? 
I think that the extra added `org.eclipse.test` bundle dependency shouldn't break any of the tests above.

**Comment by srikanth-sankaran** [comment]
> > Should be doable to fix the dependencies by adding `org.eclipse.test` to the bundle manifests above
> 
> @akurtakov : could you please look at that tomorrow, I have to finish my work day now? I think that the extra added `org.eclipse.test` bundle dependency shouldn't break any of the tests above.

After pulling in these changes I have these errors:

```
Description	Resource	Path	Location	Type
Bundle 'org.eclipse.test' cannot be resolved	MANIFEST.MF	/org.eclipse.jdt.core.tests.builder/META-INF	line 15	Plug-in Problem
Bundle 'org.eclipse.test' cannot be resolved	MANIFEST.MF	/org.eclipse.jdt.core.tests.compiler/META-INF	line 22	Plug-in Problem
Bundle 'org.eclipse.test' cannot be resolved	MANIFEST.MF	/org.eclipse.jdt.core.tests.model/META-INF	line 20	Plug-in Problem

```

Working with @jarthana to figure out how to unblock myself.

**Comment by iloveeclipse** [comment]
> After pulling in these changes I have these errors

org.eclipse.test project should be imported into workspace.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/bundles/org.eclipse.test

**Comment by akurtakov** [comment]
PlatformURLSessionTest completed normally in https://download.eclipse.org/eclipse/downloads/drops4/I20240923-1800/testResults.php thus closing.

**Comment by srikanth-sankaran** [comment]
> > After pulling in these changes I have these errors
> 
> org.eclipse.test project should be imported into workspace. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/bundles/org.eclipse.test

That addresses those 3 errors, but I have a few more new ones now:

```
Description	Resource	Path	Location	Type
Bundle 'org.jsoup' cannot be resolved	MANIFEST.MF	/org.eclipse.platform.doc.tips/META-INF	line 13	Plug-in Problem
Document cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 54	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 60	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 84	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 87	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 88	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 96	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 96	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 113	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 116	Java Problem
Element cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 131	Java Problem
Elements cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 56	Java Problem
Elements cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 86	Java Problem
Elements cannot be resolved to a type	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 115	Java Problem
Jsoup cannot be resolved	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 54	Java Problem
The import org.jsoup cannot be resolved	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 34	Java Problem
The import org.jsoup cannot be resolved	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 35	Java Problem
The import org.jsoup cannot be resolved	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 36	Java Problem
The import org.jsoup cannot be resolved	HtmlExtractor.java	/org.eclipse.platform.doc.tips/src/org/eclipse/platform/doc/tips	line 37	Java Problem

```

Is there a list of projects that are needed from platform.releng.aggregator somewhere ? Sorry a bit clueless (a lot clueless actually :) )

**Comment by jarthana** [comment]
> > After pulling in these changes I have these errors
> 
> org.eclipse.test project should be imported into workspace. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/bundles/org.eclipse.test

I generally download the eclipse-test-framework-*.zip and install the plug-ins from there. Interestingly, I am not finding the framework on the downloads page at all for 4.34 builds. Should I raise a bug or this is intentional?

**Comment by srikanth-sankaran** [comment]
I was able to close the `org.eclipse.platform.doc.tips` project and the errors have vanished. Is that OK ?

**Comment by iloveeclipse** [comment]
> That addresses those 3 errors, but I have a few more new ones now:

Simply close org.eclipse.platform.doc.tips project, you don't need it.

**Comment by srikanth-sankaran** [comment]
> > That addresses those 3 errors, but I have a few more new ones now:
> 
> Simply close org.eclipse.platform.doc.tips project, you don't need it.

Cool, done, works :)

**Comment by akurtakov** [comment]
> > > After pulling in these changes I have these errors
> > 
> > 
> > org.eclipse.test project should be imported into workspace. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/bundles/org.eclipse.test
> 
> I generally download the eclipse-test-framework-*.zip and install the plug-ins from there. Interestingly, I am not finding the framework on the downloads page at all for 4.34 builds. Should I raise a bug or this is intentional?

Install org.eclipse.test feature via p2 from the I-build update site. It is intentionally removed via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2337 as a continuation of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2332 (which didn't go smooth either due to too convoluted build system).

**Comment by srikanth-sankaran** [comment]
Alright, thanks gentlemen for your help.

**Comment by merks** [comment]
> Is there a list of projects that are needed from platform.releng.aggregator somewhere ? Sorry a bit clueless (a lot clueless actually :) )

I find it is always valuable to have a workspace with everything in it:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

**Comment by srikanth-sankaran** [comment]
@mpalat - Please look at this thread for the problems you are facing.

**Comment by iloveeclipse** [comment]
Thanks @HeikoKlare for great hint & @akurtakov for the PR's!

**Comment by merks** [comment]
And thanks everyone for the effective and respectful teamwork!  🥇

**Comment by mpalat** [comment]
Thanks everyone - saved a lot of time!
