### ISSUE TITLE
Javax.sound package not accessible

### ISSUE THREAD

**Issue by lambdacore12** [eclipse-platform/eclipse.platform#1567]
I just created my first Java project and I get the error "The package javax.sound is not accessible."

I have looked throughout the internet and added "requires java.desktop" in modul-info.java.

I am using the latest ECLIPSE IDE 2024-09.

![image](https://github.com/user-attachments/assets/fb46972c-7f5d-47b3-89d7-cb1aaedd0f16)

**Comment by akurtakov** [comment]
First of all, this is Java specific issue thus has to be reported to https://github.com/eclipse-jdt/ not to Eclipse platform.
But more important - you would have to be far more detailed in what you did exactly, what the expectation is and so on as the report in it's current form is non-actionable.
I'm closing this one as GH doesn't support moving issues between GH orgs thus a new and detailed one would be needed in jdt.

**Comment by lambdacore12** [comment]
Thank you. I don't think this issue needs more explaining: importing javax.sound gives an error, that's all.
