### ISSUE TITLE
Race condition in AutoBuildJob sometimes prevents an AutoBuildJob to be scheduled() even though buildNeeded is true

### ISSUE THREAD

**Issue by xpomul** [eclipse-platform/eclipse.platform#158]
It can happen that the AutoBuildJob's `buildNeeded` flag is `true`, but the AutoBuildJob is not scheduled and not executed until the next workspace change.

This one seems to have been in the code since forever and obviously was not noticed before (similar to [Bug 575486](https://bugs.eclipse.org/bugs/show_bug.cgi?id=575486) - AutoBuildJob booleans need volatile modifier maybe?).

We have detected it in a custom IDE in which we run (RCPTT) UI tests that changes a file, saves that file, and waits for the result of the (auto) build to show in the (custom) UI. In the UI test case, this change-save-verify cycle is multiple times in quick succession. It fails randomly, and the analysis shows the following:

Since the AutoBuildJob is scheduled even if `buildNeeded` is false, there is a good chance that it is currently running when we save a file in the test case (as at least the test case will simulate user interaction very quickly. Most likely in daily use, the users won't experience or notice this behavior, because it should occur so rarely in the case of human interaction...).

Since saving a file is done in a ISchedulingRule, and since the build is also locking the workspace, there is some synchronization happening (which makes the phenomenon even more random most likely) but the following can still happen:

The AutoBuildJob, executing in the "Building..." thread, reaches [line 176](https://github.com/eclipse-platform/eclipse.platform/blob/master/resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/events/AutoBuildJob.java#L176) which releases the workspace lock. But the Job is still in state RUNNING.

Now at this point, the main Thread is saving the file and at the end, it calls `AutoBuildJob.build(true)` from `org.eclipse.core.internal.events.BuildManager.endTopLevel()`. In the `build()` method, the `buildNeeded` flag is set to `true` and then the method checks the state of the AutoBuildJob and finds that it is currently (still) in the RUNNING state, so it does not schedule it again (it falls through the switch in [line 98](https://github.com/eclipse-platform/eclipse.platform/blob/master/resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/events/AutoBuildJob.java#L98)).

In this situation, the AutoBuild is not scheduled even though it is marked as being in need of a build. 
So until the next workspace change triggering a build, this situation won't change and the AutoBuildJob will not be executed.

I was able to work around this in our own code by adding an IJobChangeListener which checks whether the AutoBuildJob is done, and if `AutoBuildJob.buildNeeded` is `true` (of course, some reflection involved here, as the AutoBuildJob is package private). If it is, I reschedule the job with `Policy.MIN_BUILD_DELAY`.

I'm currently unsure, how a sustainable solution could look like. The AutoBuildJob code is rather old and changes could break existing synchronization efforts or reduce auto build performance.

If you have any ideas, I'd be happy to discuss them.

**Comment by jukzi** [comment]
Whenever buildNeeded is set to true it should schedule autobuild job again, which would make sure it is at least executed once more. If meanwhile buildNeeded is consumed to false the next autobuild job should just do nothing.
just add it to AutoBuildJob.build() and refactor buildNeeded = false in doBuild () into an atomic swap

**Comment by xpomul** [comment]
@jukzi Thanks for the quick reply :-)

I've had another look - especially about 

> and refactor buildNeeded = false in doBuild () into an atomic swap

Actually, the atomic swap is already there: [line 160](https://github.com/eclipse-platform/eclipse.platform/blob/master/resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/events/AutoBuildJob.java#L160) executes `shouldBuild()` which is synchronized and reads and resets the boolean flags. (and `build()` is also synchronized, so we should be safe here).

I'm wondering about the additional `buildNeeded = false` in [line 169](https://github.com/eclipse-platform/eclipse.platform/blob/master/resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/events/AutoBuildJob.java#L169) now.
It seems to have been there since before the git migration in 2007. But I cannot see its purpose. If `shouldBuild()` a few lines above already resets the flags, why resetting here again? Should I just remove this line? Or did I miss something?

**Comment by xpomul** [comment]
I have updated my change now - see resolved conversations for details.
In short:
- I have added a comment about the hidden flag reset in shouldBuild()
- I have slightly modified my initial implementation to keep it as non-invasive as possible and reschedule only if buildNeeded is true

With this, I have run our UI tests over the weekend and the race condition seems solved.

**Comment by iloveeclipse** [comment]
Funny enough, we see this bug now too in our automated tests (sporadically), where the code from UI thread requests rebuild but autubuild isn't triggered at all.
