### ISSUE TITLE
org.eclipse.equinox.launcher.cocoa.macosx bundle missing from update site

### ISSUE THREAD

**Issue by PatrickTasse** [eclipse-platform/eclipse.platform#1594]
Getting this new error when building our project with the 4.34 I-build for 2024-12 M2:

Installing org.eclipse.tracecompass.rcp 10.1.0.202410221825.
Installation failed.
Cannot complete the install because one or more required items could not be found.
	Software being installed: Trace Compass 10.1.0.202410221825 (org.eclipse.tracecompass.rcp 10.1.0.202410221825)
	Missing requirement for filter properties ~= $0: org.eclipse.tracecompass.rcp.executable.cocoa.macosx.aarch64 10.1.0.202410221825 requires 'org.eclipse.equinox.p2.iu; org.eclipse.equinox.launcher.cocoa.macosx 0.0.0' but it could not be found
	Cannot satisfy dependency:
		From: Trace Compass 10.1.0.202410221825 (org.eclipse.tracecompass.rcp 10.1.0.202410221825)
		To: org.eclipse.equinox.p2.iu; toolingorg.eclipse.tracecompass.rcp.application [10.1.0.202410221825,10.1.0.202410221825]
	Cannot satisfy dependency:
		From: toolingorg.eclipse.tracecompass.rcp.application 10.1.0.202410221825
		To: org.eclipse.equinox.p2.iu; org.eclipse.tracecompass.rcp.executable.cocoa.macosx.aarch64 [10.1.0.202410221825,10.1.0.202410221825]

If I understand correctly, org.eclipse.tracecompass.rcp.executable.cocoa.macosx.aarch64 requires org.eclipse.equinox.launcher.cocoa.macosx.

But the 4.34 I-build update site does not have that bundle:

https://download.eclipse.org/eclipse/updates/4.34-I-builds/I20241022-0640/plugins/
org.eclipse.equinox.launcher.cocoa.macosx.aarch64_1.2.1100.v20240722-2106.jar
org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.1100.v20240722-2106.jar

While the 4.33 Release update site had the bundle:

https://download.eclipse.org/eclipse/updates/4.33/R-4.33-202409030240/plugins/
org.eclipse.equinox.launcher.cocoa.macosx.aarch64_1.2.1100.v20240722-2106.jar
org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.1100.v20240722-2106.jar
org.eclipse.equinox.launcher.cocoa.macosx_1.2.1100.v20240722-2106.jar

**Comment by HannesWell** [comment]
> Fixed by upgrading from Tycho 4.0.3 to Tycho 4.0.9.

Yes exactly. Tycho 4.0.9 is required to build 4.34 products for Mac:
https://github.com/eclipse-equinox/equinox/pull/622#issuecomment-2362364255

**Comment by Phillipus** [comment]
> > Fixed by upgrading from Tycho 4.0.3 to Tycho 4.0.9.
> 
> Yes exactly. Tycho 4.0.9 is required to build 4.34 products for Mac: [eclipse-equinox/equinox#622 (comment)](https://github.com/eclipse-equinox/equinox/pull/622#issuecomment-2362364255)

But SWT build is currently using 4.0.8? See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1488

**Comment by HannesWell** [comment]
> But SWT build is currently using 4.0.8? See eclipse-platform/eclipse.platform.swt#1488

Yes, but SWT doesn't build a product for Mac does it? And when one consumes SWT the current Tycho version works well, doesn't it? 
So one has to pay attention here, but everything should work.
