### ISSUE TITLE
surefire.forkNumber undefined variable

### ISSUE THREAD

**Issue by r6squeegee** [eclipse-platform/eclipse.platform#1604]
surefire.forkNumber generates an error when junit test is run from with in eclipse.

Basically in a pom.xml surefire plugin section, you can configure to fork. This works on the command line using mvn directly, this also worked in prior versions of eclipse. I'm unsure when it broke but I think it was with in the last month or so.

Reverting back to a much earlier version of eclipse (the only one I had was 2024-03) shows it worked back then.

The reason I didn't notice it the day it happened was because you must right click the project -> maven -> update project, before it breaks (or after you install a new eclipse), if your system was working with an older version it would continue working until you had to do an update-project.

attached as a simple project showing this.

![screen](https://github.com/user-attachments/assets/31ecf4c9-fcab-499d-b99b-c9710b51dc1d)
[temp.zip](https://github.com/user-attachments/files/17604611/temp.zip)

**Comment by r6squeegee** [comment]
I should add, to un-break it, you have to downgrade to an older version of eclipse and delete the working directories .metadata directory or it will continue to appear broken even on older versions.

**Comment by merks** [comment]
I've seen this in other projects where in the pom.xml you've configure it use certain system properties and m2e seems to thing that should be converted to use a string substitution in the launcher.  You could define the value in Window -> Preferences -> Run/Debug -> String Substitutions.

In any case, this isn't something the Platform can fix.  You might ask the m2e folks about this, but with details of how one might reproduce the problem:

https://github.com/eclipse-m2e/m2e-core

**Comment by r6squeegee** [comment]
thanks, I've sent it that way.
for anyone finding this bug on google it's : https://github.com/eclipse-m2e/m2e-core/issues/1884
