### ISSUE TITLE
Too many worker threads

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#163]
When the same Job is scheduled again and again the number of worker threads grows. 
At least not as much as schedules, but why spawn  dozen of workers when there is only a single job to execute anyway?
Happens in JobManager.pool.jobQueued() during .JobManager.endJob() if reschedule.

Effect is visible during Junit Bug_574883.

BTW chances that Junit Bug_574883 fail decrease a lot if there is only 2 workers. Less workers would not fix the problem of https://github.com/eclipse-platform/eclipse.platform/issues/160 but hide it :-(

**Comment by iloveeclipse** [comment]
We have another severe regression due #187, see https://github.com/eclipse-platform/eclipse.platform/issues/227
