### ISSUE TITLE
Add Support for Importing IntelliJ IDEA Formatting and Optimize Imports Settings in Eclipse

### ISSUE THREAD

**Issue by mehmedmaljoki** [eclipse-platform/eclipse.platform#1631]
- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

From a fresh installation and clean workspace:

I reach state:

1. Open Eclipse.
2. Go to Window → Preferences → Java → Code Style → Formatter.
3. Attempt to import formatting settings.
Currently, Eclipse only supports importing formatting settings from Eclipse .xml configuration files. There is no option to directly import formatting and optimize imports settings from IntelliJ IDEA.

And would like to be able to:
I would like to have an option to import IntelliJ IDEA formatting settings (code style rules, optimize imports configurations, etc.) directly into Eclipse. This would greatly enhance usability for teams that work with mixed IDE environments and improve collaboration between developers using different tools.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
This repo is for general Eclipse Platform. Please report this issue to the sub-project dedicated to Java development: Eclipse JDT at https://github.com/eclipse-jdt/eclipse.jdt.ui/
