### ISSUE TITLE
Strange Message On Console While Debugging

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-platform/eclipse.platform#1646]
Since I upgraded to ECLIPSE 4.33, when I start a debugging session,
I get a funny message that I do not understand in the console:

2024-11-28 16:36:03.475 java[4765:5173948] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-28 16:36:03.475 java[4765:5173948] +[IMKInputSession subclass]: chose IMKInputSession_Modern

What is it? An error message or just a message?
Screenshot:
![DebugConsoleExclipse](https://github.com/user-attachments/assets/b1fc5ef5-c681-4270-bb29-6fe37cbe3331)

Thanks for reading,
;JOOP!

**Comment by Phillipus** [comment]
This happens on macOS Sequoia. It's not just on Java. If you Google it, you'll see other frameworks give that message.

**Comment by Sciuriware** [comment]
Assumed it is harmless .... OK
;JOOP!
