### ISSUE TITLE
Run On Server Option Not Visible

### ISSUE THREAD

**Issue by zugarepravin** [eclipse-platform/eclipse.platform#1649]
Run On Server Option Not Visible

I have configured eclipse-jee-2024-12-R-win32-x86_64 with Tomcat11.
I dont see "Run on Server" option to run Dynamic Web Projects. 
eclipse-jee-2024-12-R-win32-x86_64 and eclipse-jee-2024-9-R-win32-x86_64 both have issue.

On other hand 
eclipse-jee-2024-06-R-win32-x86_64 with Tomcat10 works fine.

PFA

![eclipse-jee-2024-06-R-win32-x86_64](https://github.com/user-attachments/assets/1bb27445-dacf-4d9d-b5dc-7b8ef5f2a9e2)
![eclipse-jee-2024-12-R-win32-x86_64](https://github.com/user-attachments/assets/562ac35c-421b-46c5-b76e-b9b3c5db6a31)

Thanks

**Comment by jukzi** [comment]
Missing launch options are often caused by a wrong project setup. Please post a minimal reproducer.

**Comment by mickaelistria** [comment]
"Run on Server" action is provided by the Eclipse WebTools and/or JEE Tools project. Please get in touch with their support channels, eg by posting this issue to https://github.com/eclipse-jeetools/webtools.javaee/issues.
