### ISSUE TITLE
41 AntUtilTests fail since I20241215-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1660]
for example
```
java.lang.AssertionError: Incorrect number of targets retrieved; should be 5 was: 1
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.ant.tests.ui.AntUtilTests.assertTargets(AntUtilTests.java:269)
at org.eclipse.ant.tests.ui.AntUtilTests.testGetIncludeTargetsComplexHierarchyAlias(AntUtilTests.java:152)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.eclipse.ant.tests.ui.testplugin.TestAgainExceptionRule$1.evaluate(TestAgainExceptionRule.java:39)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241215-1800/testresults/html/org.eclipse.ant.tests.ui_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

can be locally reproduced:
![image](https://github.com/user-attachments/assets/6777835c-027f-412d-842c-d2a816087818)

**Comment by jukzi** [comment]
I could not figure out which commit it broke. But i see this may be related to one ore more commits of `[ANT] Only attempt to set SecurityManager when it is supported` across multiple repositories:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623
@HannesWell

**Comment by merks** [comment]
I think we are going to need adjustments now that we are running with Java 21.  I do see things like this in the log while running the test suite:
```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:430)
	at org.eclipse.ant.internal.ui.model.AntModel.parseDocument(AntModel.java:367)
	at org.eclipse.ant.internal.ui.model.AntModel.reconcile(AntModel.java:302)
	at org.eclipse.ant.internal.ui.model.AntModel.getProjectNode(AntModel.java:1417)
	at org.eclipse.ant.internal.ui.model.AntModel.getProjectNode(AntModel.java:1425)
	at org.eclipse.ant.internal.ui.editor.text.AntFoldingStructureProvider.updateFoldingRegions(AntFoldingStructureProvider.java:92)
	at org.eclipse.ant.internal.ui.editor.AntEditor.projectionEnabled(AntEditor.java:1154)
```

**Comment by akurtakov** [comment]
While adjustments for Java 21 will most likely be needed, these tests failed even before the switch to Java 21 e.g. in https://download.eclipse.org/eclipse/downloads/drops4/I20241215-1800/testResults.php .

**Comment by HannesWell** [comment]
> I could not figure out which commit it broke. But i see this may be related to one ore more commits of `[ANT] Only attempt to set SecurityManager when it is supported` across multiple repositories: [eclipse-platform/eclipse.platform.releng.aggregator#2623](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623) @HannesWell

I also assume it's comming from the ANT change and noticed it already while looking at yesterdays I-build results, just didn't have the time to investigate. Try to do it this evening.

**Comment by jukzi** [comment]
The junit passes locally when i remove `System.setSecurityManager(` in org.eclipse.ant.internal.ui.model.AntModel.parseDocument(IDocument). Most probably some JDK argument was changed to not silently skip it.

**Comment by HannesWell** [comment]
> The junit passes locally when i remove `System.setSecurityManager()` in `org.eclipse.ant.internal.ui.model.AntModel.parseDocument(IDocument)`. Most probably some JDK argument was changed to not silently skip it.

Good point. It could also be that just an additional log-message from
https://github.com/eclipse-platform/eclipse.platform/blob/72453fed0711a571250a5078c3abfca4639835b6/ant/org.eclipse.ant.ui/Ant%20Tools%20Support/org/eclipse/ant/internal/ui/model/AntModel.java#L377

breaks the test. At least the ANT-core tests are quite sensitive.

Maybe you can re-use the constant introduced in https://github.com/eclipse-platform/eclipse.platform/pull/1655, to skip setting the security-manager when it's not supported.
Please also note that besides explicit VM-arguments also the version of the JDK to run Eclipse influences the behaviour:
Since Java-18 the default is disallow. So without any explicit arguments, the SecurityManger is disallowed when switching from java-17 to 21.

**Comment by merks** [comment]
FYI, I tested reusing the same logic from 1655 and that fixes the problem.  I think these two other places should have the same guard as the first place:

![image](https://github.com/user-attachments/assets/77fc5534-f901-4eaf-9d11-c93b5ec0bd56)

I don't want to copy the logic 3 times.  Maye it can be made public and reused (internally)?

**Comment by merks** [comment]
I believe this problem is fixed.
