### ISSUE TITLE
[mac] ua.tests DNF I20241217-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1665]
Both mac build:
![image](https://github.com/user-attachments/assets/9154664a-1782-4219-b3a5-9cf2c1d2ac8c)
https://download.eclipse.org/eclipse/downloads/drops4/I20241217-1800/testResults.php

**Comment by akurtakov** [comment]
This depends on EF infra team to provide **both arm64 and x86_64** JVMs as they change it to one or another. 
I would appreciate if someone explains it better than me at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5436 as so far I fail.

**Comment by jukzi** [comment]
cc @HannesWell because of arm64

**Comment by akurtakov** [comment]
Results to be seen in https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/43/
