### ISSUE TITLE
Unusual badge on Eclipse dock icon on Mac

### ISSUE THREAD

**Issue by mbaumbach** [eclipse-platform/eclipse.platform#170]
Just upgraded to 2022-09 and I get this badge at all times on the Mac:

<img width="81" alt="image" src="https://user-images.githubusercontent.com/48250/190287473-97bbec2c-64a7-441c-9fcb-2f072fedd8de.png">

I'm not sure what the purpose is, but is there a way to turn it off or is this a bug? Usually these badges are reserved to show numbers and indicate unread/incomplete items.

Environment:
Eclipse 2022-09 Arch
macOS Monterey 12.6
MacBook Pro M1

**Comment by akurtakov** [comment]
@sravanlakkimsetti @lshanmug could you help with this one?

**Comment by merks** [comment]
You can disable it via the check mark underlined below:

![image](https://user-images.githubusercontent.com/208716/190324433-2bc39e83-cd03-4214-8f05-b6a8bc5c8bdc.png)

This behavior changed as a result of this Oomph Bugzilla:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=580693

**Comment by mbaumbach** [comment]
Thanks @merks! I can confirm unchecking that or clearing the workspace name value out made the badge go away.

**Comment by merks** [comment]
@mbaumbach You're welcome.  Sorry for this surprising change of behavior.  You can't please all of the people all of the time. 😢
