### ISSUE TITLE
[TEAM] (Local History view) Get Contents of the current revision zeroes out the file

### ISSUE THREAD

**Issue by TIBCOeddie** [eclipse-platform/eclipse.platform#178]
Eclipse 4.24

We saw this in our product, however I then realized it seems to be a platform issue.
I reproduced as follows:
Have eclipse platform + JDT
Create a java class
Find java file, ask for Local History
in the history view, right click the bold entry (the latest/current), select Get Contents
observe the file got zeroed out (contents are blanked)

**Comment by mickaelistria** [comment]
Reproduced with latest I-Build, but I think it's a particular case of Java file creation. In other circumstances, Get Contents works fine with me.

**Comment by TIBCOeddie** [comment]
What's interesting is how our custom file type/editor also suffered from this - ending up with a blank file.

**Comment by mickaelistria** [comment]
My bad, you're probably right. I tried more carefully and could also reproduce it with other files. I most likely didn't test correctly earlier.
Are you willing to investigate this issue and maybe submit a fix?

**Comment by TIBCOeddie** [comment]
OK, basic workspace/java stuff. Not sure when (if?) this has changed in some ... past version.

Note, I'm on MacOS, running Eclipse here under Java 11.

The history view is doing simple things: file.setContents using an input stream against the same file it's going to write to. We could circumvent the bug here; do not try to do anything when the current revision/store is just the pointer to the actual file. Fix in team.

Still, maybe worth pursuing over in core land - org.eclipse.core.internal.utils.FileUtil.transferStreams(InputStream, OutputStream, String, IProgressMonitor) , basically if the input stream and the output stream point to the same file, the FileInputStream read will return -1 immediately (since the FileOutputStream is read first, truncating the file contents). Thoughts on pursuing anything there? (at least javadoc in IFile.setContents ? In case callers could assume the new contents will be read first?))

**Comment by mickaelistria** [comment]
Looks like `transferStreams` and `setContents` do what's expected from them and that we cannot reliably add checks to prevent from overriding while reading/writing (because we don't really know anything about the streams at that point). I believe that `getContentsAction` should simply be disabled or do nothing in case it's on the current revision.

**Comment by TIBCOeddie** [comment]
PR #183
