### ISSUE TITLE
Please enable Github discussions for this repository

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#194]
@vogella can you please ask as a project lead to enable github discussions for this repository as it seems more appropriate than using issues for that.

**Comment by mickaelistria** [comment]
I'd be fine with it; but I'd rather ask @akurtakov first about whether this should be approved by PMC or if we can just proceed?

**Comment by laeubi** [comment]
Also some platfrom repos already have discussions enabled... so I think there should be no general concern?

**Comment by laeubi** [comment]
Hm.. either this was very fast or something going on already? I see discussions are enabled now:

https://github.com/eclipse-platform/eclipse.platform/discussions

thanks to how ever has performed that :-)

**Comment by akurtakov** [comment]
I had the discussions "tab" visible there so I just clicked a button :).
