### ISSUE TITLE
Eclipse is crashing in SUSE platform 

### ISSUE THREAD

**Issue by vishnusarathashling** [eclipse-platform/eclipse.platform#212]
Eclipse is crashing in SUSE platform.
 * We observe the issue with eclipse platform version 4.24. With 4.23 we don't see the issue.
 * **OS - Type, distribution and version** 
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"
* The log says : **JVM terminated, Exit code=127**

**Comment by vishnusarathashling** [comment]
@iloveeclipse @jukzi @akurtakov

**Comment by akurtakov** [comment]
Also SLES 15 has been released 4 years ago and 12 is no longer on our target env list https://www.eclipse.org/projects/project-plan.php?planurl=http://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_25.xml#target_environments%20plan

**Comment by vishnusarathashling** [comment]
> You would have to tell us a lot more before your report could be actionable at least in theory. Does it happen with 4.25? What are the steps to reproduce the crash? Would you please attach the hs_err_pid* file generated by the JVM?

The eclipse was crashing when we are opening a workspace, sorry I missed to add the step. Ok anyways thanks for the info you shared.

**Comment by akurtakov** [comment]
> When the JVM crashes you should report it to the JVM vendor and hope you got a service contract.

@jukzi JVM crash happens more often due to bugs in SWT than bugs in the JVM itself. 
@vishnusarathashling In general such bugs are of interest for the project and we try to fix them if they are reproducible with latest Eclipse version and on recent OS as having a huge support matrix is beyond our manpower.

**Comment by vishnusarathashling** [comment]
> > When the JVM crashes you should report it to the JVM vendor and hope you got a service contract.
> 
> @jukzi JVM crash happens more often due to bugs in SWT than bugs in the JVM itself. @vishnusarathashling In general such bugs are of interest for the project and we try to fix them if they are reproducible with latest Eclipse version and on recent OS as having a huge support matrix is beyond our manpower.

Thats sounds perfect! Thanks @akurtakov I will try with latest eclipse and update.

**Comment by vishnusarathashling** [comment]
I tried with the latest eclipse (2022-09, platform 4.25) and I am getting the same crash. 
Steps to reproduce:
* Installed "Eclipse IDE for C/C++ Developers" (2022-09)
* Opened a workspace
* Import a project.
* Right click the imported project. 

**Platform details below:**
OS - Type, distribution and version 
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"

**Comment by iloveeclipse** [comment]
SLES 12 **is not supported**, see above

**Comment by promodkumarCM** [comment]
I too face the same issue in SLES 12, sorry to hear that we don't have support for that.

**Comment by vishnusarathashling** [comment]
@iloveeclipse @akurtakov @jonahgraham @jukzi 
I had to work on this issue and found that the changes in the commit : https://github.com/eclipse-platform/eclipse.platform.swt/commit/d8e3f297ffde54412d935db7dde31d276b58b635#diff-874667bd88035dc47251befdad240fb5cf39f7db50597060fe17c2ecb6082de5 has caused this issue. But this commit seems to be added intentionally making the min version of GTK to 3.22. The crash occurs when we are right clicking (when trying to show a pop up menu) - getting gtk_menu_popup_at_pointer undefined symbol. Since this may not be present in gtk4. Earlier we used to have a separate handling if the gtk version was less than 3.22. I tried to add the removed native call and changes in Menu.java, Device.java and Shell.java and the right click functionality is working fine now. 

I had to build the .so files used for gtk.linux locally for this. When I was doing that I created the .so files using 
`eclipse.platform.swt\bundles\org.eclipse.swt\bin\library\build.sh -gtk3 install` command. The output .so files will be created using GTK3 binding (eg: libswt-pi3-gtk-4960r6.so ) and it will not have the .so corresponding to GTK4 binding (expected as per the documentation). 
* But will these .so files work for any platform (when the final product is installed) where the GTK version installed is GTK4. I am afraid that it will fail at some native calls for GTK4 (as I see we have GTK4 native calls made from  different UI java classes).
* When I checked the latest eclipse platform, it also contains only the "libswt-pi3-gtk-4960r6.so" (and no libswt-pi4-gtk-4960r6.so) in org.eclipse.swt.gtk.linux.x86_64.jar. So I just wanted to confirm during eclipse build also we are using -gtk3 and e haven't moved to gtk4 still. Please correct me if I am wrong at some point.

**Comment by jonahgraham** [comment]
@vishnusarathashling I wanted to let you know that I saw your comment/questions. But I don't have anything really to offer here. The mentioned commit did indeed make the min version 3.22 nearly 7 years after GTK 3.22 was released. As you can see from the commit, the reason for doing this was in part to remove lots of special case code.

All I can recommend is if you need GTK < 3.22 that you continue to use SWT / Platform that was released before this change. Of course if you want to rebuilt SWT for your own use as you have started to do, you are welcome to. But I don't think there is time from the people you tagged to support this old version of GTK with a new version of Eclipse.

**Comment by vishnusarathashling** [comment]
Thanks @jonahgraham I got your point, but I am in real need of latest eclipse support with GTK3.20. So I have no way other than going with the build. Actually I am able to build it and it's working fine in 3.20. But I have a question like I built the .so files  using
`eclipse.platform.swt\bundles\org.eclipse.swt\bin\library\build.sh -gtk3 install` command. The output .so files will be created using GTK3 binding (eg: libswt-pi3-gtk-4960r6.so ) and it will not have the .so corresponding to GTK4 binding (expected as per the documentation).
* But will the .so files (built using gtk3 option) work for any platform where the GTK version installed is GTK4?
* When I checked the latest eclipse platform, it also contains only the "libswt-pi3-gtk-4960r6.so"  (and no libswt-pi4-gtk-4960r6.so) in org.eclipse.swt.gtk.linux.x86_64.jar. So I just wanted to confirm that during eclipse swt build process also we are using -gtk3 and we haven't moved to gtk4 still. Please correct me if I am wrong at some point ie: Since eclipse latest version is also coming with gtk3 built .so (like  libswt-pi3-gtk-4960r6.so), will it work in a platform where we have gtk4 installed?

**Comment by laeubi** [comment]
@vishnusarathashling maybe it would help to open a PR with the changes you made? Maybe they are simple enough to be included in the current SWT code, I assume it is not required to redo the whole commit but just adjust some code pathes?
