### ISSUE TITLE
Extreme slowdown of job scheduling with I20221013-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#227]
I'm currently investigating a crash in our application test that used to run in **~7** minutes but since I've updated platform to I20221013-1800 it runs **over ~50** minutes (if not killed by test framework before).

The test tests code that as (a result of test interactions) constantly re-schedules (~10) short living UI jobs. 

It seems that either the job scheduling or job execution is now extremely slow for this use case.

I've bisected that to https://github.com/eclipse-platform/eclipse.platform/pull/187/ / commit fc49c4ffaf8a6c07b58e437c62125203f80028f2.

**Comment by iloveeclipse** [comment]
@jukzi : I've pushed https://github.com/eclipse-platform/eclipse.platform.ui/pull/414 which shows the problem with https://github.com/eclipse-platform/eclipse.platform/pull/187 / commit https://github.com/eclipse-platform/eclipse.platform/commit/fc49c4ffaf8a6c07b58e437c62125203f80028f2 and `UIJob` implementation.

Feel free to improve.

Note: https://github.com/eclipse-platform/eclipse.platform/pull/229 doesn't fix that.

**Comment by jukzi** [comment]
thanks, thats interesting. i was not aware of job could end in  the UI thread instead of a worker. that is fixable

**Comment by jukzi** [comment]
i adapted 229

**Comment by mickaelistria** [comment]
Is this issue still present with latest #229 merged?

**Comment by iloveeclipse** [comment]
> Is this issue still present with latest #229 merged?

This issue seem to be fixed, however I see other crashes related to job framework, I'm investigating.
