### ISSUE TITLE
Installing plugins and features using dropins doesn't work

### ISSUE THREAD

**Issue by minemeraj** [eclipse-platform/eclipse.platform#231]
Steps to produce:
1. Download eclipse sdk the latest build: https://download.eclipse.org/eclipse/downloads/drops4/S-4.26M1-202209281800/
2. download subclipse update site zip from here: https://github.com/subclipse/subclipse/releases
3. copy the subclipse features and plugins to eclipse/dropins folder
4.  start eclipse sdk with -clean argument

The subclipse plugins or features are not installed.

I know from this document https://wiki.eclipse.org/Equinox/p2/Getting_Started#Supported_dropins_formats that it is recommended to use p2 UI but this is not possible for my case. I have to get the dropins working for our case.

Dirs:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/2042835/196397413-f156478e-4b68-4be2-adfe-aa7106f927a9.png">

Plugin list:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/2042835/196404481-156273e3-1564-41c1-8a81-d45a787ed390.png">

**Comment by mickaelistria** [comment]
Try Show View > Console, then from the Console View on its top right icon, open the "Host OSGi console" and try some command such as `bundle <some subclipse bundle name>` to see whether it's installed. If it is installed, just try to start it with `start ...` command and you'll see why it's not starting.
It's very likely a dependency issue. Dependency issues are almost not avoidable when using dropins. p2 is meant to avoid those.

**Comment by minemeraj** [comment]
> Try Show View > Console, then from the Console View on its top right icon, open the "Host OSGi console" and try some command such as `bundle <some subclipse bundle name>` to see whether it's installed. If it is installed, just try to start it with `start ...` command and you'll see why it's not starting. It's very likely a dependency issue. Dependency issues are almost not avoidable when using dropins. p2 is meant to avoid those.

The bundle command seems not working, I normally use ss. but it is not showing up at all.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/2042835/196408564-7daf467e-af35-4a79-a717-a91b513ea3da.png">

**Comment by minemeraj** [comment]
> Try Show View > Console, then from the Console View on its top right icon, open the "Host OSGi console" and try some command such as `bundle <some subclipse bundle name>` to see whether it's installed. If it is installed, just try to start it with `start ...` command and you'll see why it's not starting. It's very likely a dependency issue. Dependency issues are almost not avoidable when using dropins. p2 is meant to avoid those.

I think you are right, there are in fact some dependency problems.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/2042835/196409658-09100a42-3946-4f32-945a-fe2109f4908c.png">


But even if I create an empty plugin with no dependency it also doesn't work.

**Comment by laeubi** [comment]
I never was able to get SVN working with recent eclipse version where it works was Photon ...

But you can use git to access/work with SVN repositories:
https://gist.github.com/rickyah/7bc2de953ce42ba07116

**Comment by akurtakov** [comment]
Due to dropins being practically a nightmare to investigate, back in the days when we were shipping Eclipse RPMs in Fedora we came with the concept of "droplet" (aka a full p2 repo and use them as local repos to provision these plugins). This was never fully upstreamed (see various patches at https://src.fedoraproject.org/rpms/eclipse/tree/f34 for details) but if you want to drop files and use them as plugins I strongly recommend investigating this path. 
For me, dropins is dead technology which we should properly deprecate actually.

**Comment by ruspl-afed** [comment]
> I never was able to get SVN working with recent eclipse version where it works was Photon ...
> 
> But you can use git to access/work with SVN repositories: https://gist.github.com/rickyah/7bc2de953ce42ba07116

We have recently released Eclipse Subversive™ SVN Team Provider 4.8.0, here is update site https://download.eclipse.org/technology/subversive/4.8/release/latest/
It was build with Eclipse Platform 4.16 (to reduce code changes after long pause).

The plan is to build it with more recent Eclipse Platform version after source migration from svn to git.

**Comment by minemeraj** [comment]
> You should use that site like this to properly install from it:
> 
> ![image](https://user-images.githubusercontent.com/208716/196446476-9147d8ea-97a1-4804-8387-3f5e675ae6f6.png)
> 
> Then you can see what fails to install:
> 
> ![image](https://user-images.githubusercontent.com/208716/196446772-7ac03559-f997-4956-9a5a-4b42b71d988d.png)
> 
> I didn't even try the Mylyn integration because it's mostly gone...
> 
> So I don't think anything is wrong with the drop-in support but it certainly doesn't provide any user feedback about why the things you put in there are failing to install or to activate.

The eclipse drop-in feature is not working. The subclips stuff I put here for just an example. My original intention was not to install subclips. Create an empty plugin with no depdendency and try to export to dropin folder, eclipse doesn't pick up the plugin. It is a bug from my point of view or at least there is somewhere some magic has to be activated.

Could you please point me to any documentation that I follow?

**Comment by merks** [comment]
It worked for me.   Here I copied some stuff from my vi-plugin site into the drops-ins folder, even using subclipse in the folder names:

![image](https://user-images.githubusercontent.com/208716/196609010-4a101b37-2cb8-4dc4-af63-16d889469088.png)

Launching that IDE, the vi toolbar button is present:

![image](https://user-images.githubusercontent.com/208716/196609154-2c605577-51c3-402b-b6da-b67db2aee49a.png)

Here's documentation:

https://wiki.eclipse.org/Equinox/p2/Getting_Started#Dropins
