### ISSUE TITLE
Reference on lambda is not found

### ISSUE THREAD

**Issue by Jan-Stolze** [eclipse-platform/eclipse.platform#239]
Lambda type hierarchy is not finding interface implementation when using ::
See code example for illustration
```
public class EclipseBug
{
  public static void main(String[] args)
  {
    new EclipseBug().printHelloWorldTypeNotFound();
  }

  public void printGreetings(GreetingsIF greeting)
  {
    System.out.println(greeting.getGreeting());
  }

  void printHelloWorldTypeNotFound()
  {
    printGreetings(this::getHelloWorldGreeting);
  }

  void printHelloWorldTypeFound()
  {
    printGreetings(() -> getHelloWorldGreeting());
  }

  private String getHelloWorldGreeting()
  {
    return "Hello world!!";
  }

  public static interface GreetingsIF
  {
    String getGreeting();
  }
}
```

![afbeelding](https://user-images.githubusercontent.com/116337002/197128612-a9c9dffb-e043-4b64-9b2a-f145f0ece086.png)

**Comment by akurtakov** [comment]
Please open this bug against https://github.com/eclipse-jdt where the Java support is implemented . GitHub doesn't allow moving issues between organizations and Eclipse platform is not the project providing Java support.
