### ISSUE TITLE
[Git History] The diff view do sometimes not display the diff content

### ISSUE THREAD

**Issue by wolfgang-ch** [eclipse-platform/eclipse.platform#264]
When a file is selected in the commit history, then sometimes the diff view do not show the diff content, only a one liner. After moving the vertical splitter (UI is resized), then the content is also displayed

https://user-images.githubusercontent.com/1283445/201009743-f1f42855-5e12-4d60-934f-fb80900ae81b.mp4

**Comment by mickaelistria** [comment]
The bug doesn't seem to come from the generic Platform history view. Please report this issue to EGit project that owns (a subset of, including the diff part) this history view: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit&component=UI .

**Comment by wolfgang-ch** [comment]
Bug created https://bugs.eclipse.org/bugs/show_bug.cgi?id=581025

**Comment by mickaelistria** [comment]
Thank you!
