### ISSUE TITLE
win: problems with deleting files during core.tests.resources since 20221108

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#265]
https://download.eclipse.org/eclipse/downloads/drops4/I20221108-1800/testResults.php
`The process cannot access the file because it is being used by another process.`
My best guess is something like a virusscanner is scanning all newly created files.

**Comment by tomaswolf** [comment]
Note that this Windows error message is misleading. It might also be that the file is open within the same process.
