### ISSUE TITLE
Failure in upload-test-result from windows GH action

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform#278]
See https://github.com/eclipse-platform/eclipse.platform/actions/runs/3506961469/jobs/5874340319

**Comment by akurtakov** [comment]
@laeubi Can you take a look?

**Comment by laeubi** [comment]
Sadly this is cause by a bug in the upload-action see:
- https://github.com/actions/upload-artifact/issues/240

The only "solution" I found was to disable the upload for windows ...

**Comment by akurtakov** [comment]
Thanks, I'll do it.
