### ISSUE TITLE
com.sun.jna_5.8.0.jar.zip/com.sun.jna_5.8.0.jar/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib is not signed with a valid Developer ID certificate

### ISSUE THREAD

**Issue by viragpurnam** [eclipse-platform/eclipse.platform#298]
Notarization fails with below error. 
`"issues": [
{
"severity": "error",
"code": null,
"path": "com.sun.jna_5.8.0.jar.zip/com.sun.jna_5.8.0.jar/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib",
"message": "The binary is not signed with a valid Developer ID certificate.",
"docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
"architecture": "arm64"
},
{
"severity": "error",
"code": null,
"path": "com.sun.jna_5.8.0.jar.zip/com.sun.jna_5.8.0.jar/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib",
"message": "The signature does not include a secure timestamp.",
"docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
"architecture": "arm64"
},
{
"severity": "error",
"code": null,
"path": "com.sun.jna_5.8.0.jar.zip/com.sun.jna_5.8.0.jar/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib",
"message": "The binary is not signed.",
"docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
"architecture": "x86_64"
},
{
"severity": "error",
"code": null,
"path": "com.sun.jna_5.8.0.jar.zip/com.sun.jna_5.8.0.jar/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib",
"message": "The signature does not include a secure timestamp.",
"docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
"architecture": "x86_64"
}
]
}`

If I try to sign manually hash code does not match.

`[ERROR]    Problems downloading artifact: osgi.bundle,com.sun.jna,5.8.0.:
[ERROR]       SHA-256 hash is not as expected. Expected: 930273cc1c492f25661ea62413a6da3fd7f6e01bf1c4dcc0817fc8696a7b07ac and found a28ab1ded05537fdc026dbabc044d101b8ab2d50929924c367c033e0d3933772.`

This issue is with Eclipse 4.26 as well. I mean com.sun.jna_5.12.1.jar as well has the same issue.

**Comment by merks** [comment]
Is this not the same issue has this one?

https://github.com/eclipse-platform/eclipse.platform/issues/293

**Comment by viragpurnam** [comment]
Yes, But SHA-256 mismatch appears when we try to sign the lib locally.  Please refer the issue raised earlier and issue was solved by signing the libs and providing patch and keeping the signed ones at orbit location. https://bugs.eclipse.org/bugs/show_bug.cgi?id=572876

Same has to be done for the latest jars as well.

**Comment by merks** [comment]
Well yes, if you sign it, you change the jar and then of course you will have to update the site's artifacts.xml with new checksums...

Still we have not gotten to the bottom of whether all the Eclipse applications are notarized and how it can be that they are notarized despite this issue.
