### ISSUE TITLE
random failing org.eclipse.core.tests.runtime.jobs.JobGroupTest.testJoinWithTimeout

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#30]
https://download.eclipse.org/eclipse/downloads/drops4/I20220522-0600/testresults/html/org.eclipse.core.tests.runtime_ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
junit.framework.AssertionFailedError: 2.0
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.core.tests.runtime.jobs.JobGroupTest.testJoinWithTimeout(JobGroupTest.java:540)
```

**Comment by akurtakov** [comment]
Do you still see this failure?

**Comment by jukzi** [comment]
> Do you still see this failure?

yes https://github.com/eclipse-platform/eclipse.platform/pull/176

**Comment by jukzi** [comment]
strange test conditions: sleep(100)*11 is certainly not ==1100ms.
Even a sleep(1) will rather last 2ms on my computer
javadoc: "subject to the precision and accuracy of system timers and schedulers"... and it can be even worse when the system is under load
