### ISSUE TITLE
Ampersand in hover text for 'Close Project' 

### ISSUE THREAD

**Issue by hsjoshi28** [eclipse-platform/eclipse.platform#304]
There is an ampersand sign in hover text displayed for 'Close Project' under the 'Project' ribbon.

![Eclipse_Close_Prokect_issue](https://user-images.githubusercontent.com/88348124/208770557-a6ff7bcb-5560-411c-bff6-c8e76dc9c465.png)

**Comment by merks** [comment]
@hsjoshi28 Thanks for reporting this issue.
