### ISSUE TITLE
IJobChangeListener with lambda for done(IJobChangeEvent event) ?

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform#313]
Is it worth to have method like

`static IJobChangeListener jobDoneAdapter(Consumer<IJobChangedEvent> c) {
       return new JobjChangedAdapter() {
                 public void done(IJobChangedEvent e) {
                      c.accept(e);
                 }
       };
}`
???

AFAICS the done method in a listener is most implemented one and having that as lambda would make coding shorter (though I have to admit with the JobChangeAdapter class it is quite short already).

But the question is, where do we stop. At the end there is a lambda for every method of IJobChangeListener. And later even for mixtures.

**Comment by laeubi** [comment]
> But the question is, where do we stop. At the end there is a lambda for every method of IJobChangeListener. And later even for mixtures.

For general discussions/ideas you can also use the https://github.com/eclipse-platform/eclipse.platform/discussions in this repository.

**Comment by marcushoepfner** [comment]
Done in https://github.com/eclipse-platform/eclipse.platform/pull/314.
