### ISSUE TITLE
Unmappable characters in filename break project import

### ISSUE THREAD

**Issue by jdneo** [eclipse-platform/eclipse.platform#335]
Original issue: https://github.com/microsoft/vscode-java-dependency/issues/712.

Reproduced steps: https://github.com/microsoft/vscode-java-dependency/issues/712#issuecomment-1415714628

Looks like when the project has utf8 characters (like `ä`) and the system encoding is not utf8, the import will be broken totally.

**Comment by iloveeclipse** [comment]
In original issue neither Eclipse workspace nor project were existing, they are most likely created by vscode/m2e. By default using latest Eclipse the problem can't happen, as we use UTF8 everywhere.

Feel free to reopen if you have steps to reproduce that actually include Eclipse as IDE, not as a library ised by some other application.
