### ISSUE TITLE
Move N&N to wiki or others means in repo

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform#343]
Including the N&N into the help is an effort for every release and delays branch switching before a release more difficult.

I suggest we stop doing this and only keep a wiki or a webpage with our release notes.

Eclipse help would only contain a link to the page. IMHO preferrable would be only one page for all release similar to what Tycho is doing so that no change in help is needed during release work.

WDYT? @laeubi @iloveeclipse @mickaelistria @akurtakov @lshanmug

**Comment by mickaelistria** [comment]
> Including the N&N into the help is an effort for every release and delays branch switching before a release more difficult.

What about we try it the other way round: we edit the N&N directly in the help, remove the other repo and make https://www.eclipse.org/eclipse/news/ reference the help?

**Comment by vogella** [comment]
> > Including the N&N into the help is an effort for every release and delays branch switching before a release more difficult.
> 
> What about we try it the other way round: we edit the N&N directly in the help, remove the other repo and make https://www.eclipse.org/eclipse/news/ reference the help?

I don't think fiddling with help and its strange extension point link system is something we will have a lot of people doing.  At least I would not touch them, so easy way to test and validate the changes. Also editing HTML directly feels like wasted time to me.  Maintaining a wiki or markdown document seems easier and more common.

**Comment by mickaelistria** [comment]
I was only mentioning that as a possible -and I would say the most direct and simplest - solution to your initial message "Including the N&N into the help is an effort for every release and delays branch switching before a release more difficult.". But it doesn't seem to be the real problem here.

**Comment by vogella** [comment]
> I was only mentioning that as a possible -and I would say the most direct and simplest - solution to your initial message "Including the N&N into the help is an effort for every release and delays branch switching before a release more difficult.". But it doesn't seem to be the real problem here.

Direct editing would only increase the effort / problem that maintaining help is a lot of effort. The solution should be to reduce the effort not make it more complex or reduce the number of people which have the knowledge / desire / skills to do so.

**Comment by mickaelistria** [comment]
> Direct editing would only increase the effort / problem that maintaining help is a lot of effort

What particularly makes you say that my proposal about editing files in the help repo directly is more effert than maintaining files in the news repo?

**Comment by akurtakov** [comment]
Having N&N in tarballs has many bad effects for me:
* extra releng steps at the very last minute
* direct editing of html which is everything else but not nice, markdown (or smth else) could be used if only web representation
* no ability to fix/imrove content post release
* clutter in the help system as there are N&N for many versions
* even slightly bigger downloads each release is a concern for me.

**Comment by laeubi** [comment]
I just wanted to link this here even though I have not used it directly:

https://github.com/release-drafter/release-drafter

Also there are tools like https://markdowntohtml.com/ if one wants to convert release notes to html somehow.

**Comment by vogella** [comment]
Dup of https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/issues/90
