### ISSUE TITLE
JobManager: Possible java.lang.ArrayStoreException in Job[] find(Object family)

### ISSUE THREAD

**Issue by zeljkoAmiq** [eclipse-platform/eclipse.platform#353]
java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, org.eclipse.core.runtime.jobs.Job
	at java.base/java.util.ArrayList.toArray(ArrayList.java:433)
	at org.eclipse.core.internal.jobs.JobManager.find(JobManager.java:732)

public Job[] find(Object family) {
		List<InternalJob> members = select(family);
		return members.toArray(new Job[members.size()]);
	}

Not every InternalJob is a Job

Proposed solution: Filter out from the list all elements which are not a Job

**Comment by merks** [comment]
The Javadoc says this:
```
/**
 * Internal implementation class for jobs. Clients must not implement this class
 * directly.  All jobs must be subclasses of the API <code>org.eclipse.core.runtime.jobs.Job</code> class.
 */
public abstract class InternalJob extends PlatformObject implements Comparable<InternalJob> {
```
So I guess you are not following that rule.  Is there a reason for not following that rule?

**Comment by iloveeclipse** [comment]
> Not every InternalJob is a Job

If code follows the contract, it is not true:

https://github.com/eclipse-platform/eclipse.platform/blob/9839c18f52687db6f949bdb56a59a5d20cd7c938/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/InternalJob.java#L30

This is since 2005 at least.

**Comment by merks** [comment]
From what I can see, the dummy instance never escapes from that internal final framework class, i.e, this is not a client of the job framework but rather an internal implementation detail...

**Comment by zeljkoAmiq** [comment]
Ok, fair enough, but this still doesn't prevent consumers of the API to use InternalJob.
Maybe at least make it package-protected? 
Today having only a "must not" note in the JavaDoc still permits others to disobey the recommendation :)

**Comment by merks** [comment]
If you use that class, you get a bunch of warnings already:

![image](https://user-images.githubusercontent.com/208716/224058095-01b868c3-7b34-4b4a-8596-76e8820febd1.png)

If people ignore, warnings, don't notice that the package is internal, and don't read any documentation, yes they can shoot themselves in the foot and will find out about that at runtime.

**Comment by zeljkoAmiq** [comment]
Ok, then why having the class public?
Is there any situation when somebody would use it and not "shoot themselves in the foot"?
If not, why to allow this?

**Comment by iloveeclipse** [comment]
> Ok, then why having the class public?

Because it is extended by a class from a different package, it can't be package protected.
