### ISSUE TITLE
Improve the way to update the contents of a file

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#354]
The discussion in
- https://github.com/eclipse-platform/eclipse.platform/issues/302

has made me wonder how one might can improve I/O performance of the resource API on a higher level and just looked a bit through the code and found a recurring pattern like this:

```
if (ExportUtil.validateEdit(shell, file)) // checkout file if required
{
	// write build file
	String html = AppletUtil.buildHTMLFile(conf);
	InputStream is = new ByteArrayInputStream(html.getBytes("UTF-8")); //$NON-NLS-1$
	if (file.exists()) {
		file.setContents(is, true, true, null);
	} else {
		file.create(is, true, null);
	}
}
```

This has two issues:

1. It is first checked if the file exits and then either the first or the second branch is executed. Not that this is cumbersome to write, it also requires me to check existence of the file even though my intend is to create it anyways and existence check is also performed in setContents (to maybe throw an exception)
2. Even if we have the bytes here they need to be wrapped in a stream (what later is the transferred to an file  output stream), and even if there are some optimizations to recover the underlying buffer, Objects are created just to garbage collect then later

So this can be improved to have a method `IFile#putContents` that simply overwrites the file or create it if it does not exits (very similar to new FileOuputStream()) and the caller do not need to do any checks, this then can even short circuit some call-path.
This can also improve code to not needing boilerplate everywhere.

Also it could be good to have variants that accept a byte array so `org.eclipse.core.filesystem.IFileStore.openOutputStream(int, IProgressMonitor)` could also have a new method to accept bytes directly, so the impl can choose what is the fastest way to put the bytes on the backing storage....

By the way I do not plan to work on this, just wanted to not loose the idea.

**Comment by HannesWell** [comment]
I think this is now implemented via
- https://github.com/eclipse-platform/eclipse.platform/pull/1420
- https://github.com/eclipse-platform/eclipse.platform/pull/1429
