### ISSUE TITLE
68 test failures in ant with java 18 from I20220326-1800

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform#4]
https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/html/org.eclipse.ant.tests.core_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html
https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/html/org.eclipse.ant.tests.ui_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html

There are 68 test failures when we run with Java 18

**Comment by sravanlakkimsetti** [comment]
@SarikaSinha Can you please investigate

**Comment by laeubi** [comment]
What I always wondered about: Maybe it is time to drop all that ant stuff? It seems platform has al migrated to tycho/maven and it seems it becomes harder and harder to support/test the ant stuff.
But maybe I just to see where it is still relevant?

**Comment by iloveeclipse** [comment]
Well, ant is still very useful to run any kind of custom build generators. Maven is nowhere near in simplicity and versatility to ant.

**Comment by laeubi** [comment]
I think any concrete examples would help more to get a better understanding.

**Comment by sravanlakkimsetti** [comment]
This feature is for supporting ant in eclipse. Platform may not use ant. but this is a very useful feature to our end customers

**Comment by laeubi** [comment]
> This feature is for supporting ant in eclipse. Platform may not use ant. but this is a very useful feature to our end customers

I see, could it be that ant is not compatible with Java 18?

**Comment by sravanlakkimsetti** [comment]
Security manager has been deprecated some versions ago but its default has been changed to not to allow in Java 18. This probably the reason why we are seeing this error

**Comment by merks** [comment]
Just do Ctrl-Shift-R and find build.xml and you'll see it's well used.  Even EMF's Tycho build uses build.xml to do stuff.   So no, I don't think it's time to drop it.

**Comment by SarikaSinha** [comment]
I could not find the logs for Java 18 run under https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/logs.php#console

**Comment by sravanlakkimsetti** [comment]
They are available here https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18/ and https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/consolelogs/ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18_consolelog.txt

**Comment by SarikaSinha** [comment]
Will be working to add the Java version checks to not execute the tests which have been removed in Java 18.
They are already deprecated but can continue to run with Java 11.

**Comment by SarikaSinha** [comment]
@sravanlakkimsetti We need to run the test with "-Djava.security.manager=allow" while executing with Java 18.
No code change required in platform.ant.

**Comment by sravanlakkimsetti** [comment]
The test job does have `-Djava.security.manager=allow` set. Do you see any problem like it was not propagated?

**Comment by SarikaSinha** [comment]
Looks like, as locally all the same failures went off after adding the argument.

**Comment by sravanlakkimsetti** [comment]
I made changes to propagate `-Djava.security.manager=allow` in tests and started recent tests again. Please check in the latest test results after 3 hours

**Comment by SarikaSinha** [comment]
I see 2 test failures now, will work on them.

**Comment by SarikaSinha** [comment]
https://github.com/eclipse-platform/eclipse.platform/pull/5
