### ISSUE TITLE
Random failing org.eclipse.core.tests.runtime.jobs.JobTest.* tests

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#402]
Several test methods in `JobTest` are randomly failing. In particular, the ones I found are:
* `testJoinInterruptNonUIThread`: https://github.com/eclipse-platform/eclipse.platform/actions/runs/4615917148/jobs/8160303205
  * This was already found and improved by increasing timeout before: https://github.com/eclipse-platform/eclipse.platform/issues/320
* `testAsynchJobConflict`: https://github.com/eclipse-platform/eclipse.platform/actions/runs/4572138024/jobs/8071083283
* `testJoinWithTimeout`: https://github.com/eclipse-platform/eclipse.platform/actions/runs/4616213598/jobs/8160940708

**Comment by HeikoKlare** [comment]
`testAsynchJobConflict` only fails because the async jobs are still running, i.e., the timeout of the barrier is simply too low on certain build systems. Should not be a problem to increase the timeout, as running into the timeout is exceptional behavior that is only relevant to ensure the build does not get stuck in case of a failure.

**Comment by iloveeclipse** [comment]
Still failing (and more often as before): 
- https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/testresults/html/org.eclipse.core.tests.runtime_ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html
- https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/testresults/html/org.eclipse.core.tests.runtime_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html
 ```
Thread not interrupted expected:<Status CANCEL: unknown code=1 > but was:<null>
junit.framework.AssertionFailedError: Thread not interrupted expected:<Status CANCEL: unknown code=1 > but was:<null>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.TestCase.assertEquals(TestCase.java:238)
at org.eclipse.core.tests.runtime.jobs.JobTest.testJoinInterruptNonUIThread(JobTest.java:1011)
```
