### ISSUE TITLE
Random failing org.eclipse.ant.tests.ui.AntUtilTests.testGetIncludeTargetsPerformance on MacOS

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#403]
`AntUtilTests.testGetIncludeTargetsPerformance` takes more than the expected maximum of 10 seconds to finish in some of the recent MacOS builds. As far as I can see there were no recent changes in the productive code, so failures may be due to too slow build infrastructure?

```
java.lang.AssertionError: Expecting a duration < 10000, but we have 12125ms
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.ant.tests.ui.AntUtilTests.testGetIncludeTargetsPerformance(AntUtilTests.java:221)
```

See:
https://github.com/eclipse-platform/eclipse.platform/actions/runs/4621006483/jobs/8171898101
https://github.com/eclipse-platform/eclipse.platform/actions/runs/4620696572/jobs/8171161377
https://github.com/eclipse-platform/eclipse.platform/actions/runs/4616360586/jobs/8161276288

**Comment by jukzi** [comment]
There may be performance degradation when the use of deprecated for removal Classes is detected and logged.

**Comment by HeikoKlare** [comment]
That would make sense. The failures occur since about the time moving to Java 17 and the Ant parser uses the `SecurityManager`, which is deprecated with Java 17.

**Comment by HeikoKlare** [comment]
I am not sure about the best option to fix this.
May we have some value added to the expected duration and make it depend on the presence of the `AntSecurityManager`? When the `AntSecurityManager` becomes removed (at latest when moving to the Java version where `SecurityManager` is removed), the parse functionality will not access the deprecated `SecurityManager` anymore and the duration change will not be required anymore. This would be enforced by an occurring compile failure upon removal of `AntSecurityManager`.

**Comment by HeikoKlare** [comment]
I could not reproduce a significant effect of the `SecurityManager` and logging warnings on the execution time.

However, the test uses the system time to evaluate performance. Since the Maven build now runs in parallel mode, several tests and thus threads associated with them can be executed in parallel. This can have significant effects on the (system) execution time of a single thread, as having it not dispatched for a significant amount of time is more likely to happen than when executing only a single test at once. Thus, this affects the timing behavior of the test method.

To get more reliable and reproducible results, I propose to measure the CPU time instead of the system time to not consider times in which the thread executing the test case has not been dispatched to any processor core.
