### ISSUE TITLE
Plugins in dropins folder not being used when launching application from eclipse.

### ISSUE THREAD

**Issue by Ferdi-S** [eclipse-platform/eclipse.platform#405]
I specify the location of my application in the "Workspace Data" area of the "Main" tab in the "Run Configurations" view, but the plugins located in my application's dropins folder are not loaded by eclipse when I start the application form eclipse.  

Is there something I need to configure in order for those plugins in the dropins folder to be loaded by eclipse?

**Comment by merks** [comment]
The Workspace Data Location is the location of the workspace.  It's not sensible to try to specify a dropins location there.  

In general, I don't think dropins locations work at all for such a launch and no one is going to make that work.  You should expect to use the Plug-ins tab to specify which plugins are supposed to be available for your application when it is launched.  You should use Window -> Preferences -> Plug-in Development -> Target Platform to create a target platform that contains any additional bundles you want to be available for your application.
