### ISSUE TITLE
LocalFileNativesManager initialisation is not flexible enough to avoid DLL Hijacking AND avoid performance degradation

### ISSUE THREAD

**Issue by feilimb** [eclipse-platform/eclipse.platform#416]
When the LocalFileNativesManager class is classloaded, initialisation code is invoked, which by default attempts to load a library named "_unixfile_1_0_0.dll_".  

This was previously documented as a security vulnerability due to the potential for a DLL Hijacking type attack, and a workaround / advisory was published here: https://www.ibm.com/support/pages/default-eclipse-settings-can-cause-potential-vulnerability 
.. and with a protected Bugzilla discussion here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558017

The issue with the workaround detailed in the above advisory is that whilst usage of the system property "_eclipse.filesystem.useNatives=false_" does indeed prevent the offending code (_UnixFileNatives.isUsingNatives()_) from being invoked, it also **_prevents_** (on a Windows system) native implementations from being benefitted from / used by the various File IO operations within the _LocalFileNativesManager_ class API itself.

This performance degradation is observed in the tool I work on, when the system property above is set, and renders the performance to be twice as slow on some operations observed.  Also not that the class description itself within _LocalFileNativesManager_ states:
```
 * Please notice that the native implementation is significantly faster than the non-native one.
 * The BenchFileStore test runs 3.1 times faster on Linux with the native code than without it.
```

I would suggest that further flexibility should be offered to avoid the invokation of _UnixFileNatives.isUsingNatives()_ but in a way that *does* still allow (on Windows) for the native implementations to be used for the File IO operations within _LocalFileNativesManager_. As far as I can see the workaround detailed in the above advisory is piggy-backing on a pre-existing flag which was incorporated relating to the testing of the code on Unix platforms.

If a new additional system property(ies) were added, it should be possible to both (a) avoid _UnixFileNatives.isUsingNatives()_ from being invoked on a Windows system, _and_ (b) allow native implementations to continue to be used for the File IO operations.

I can create a proposal for a fix if that is useful.

**Comment by jukzi** [comment]
This issue sound almost like a duplicate of https://github.com/eclipse-platform/eclipse.platform/issues/168 ?
Please contribute a fix.
As far as i understand a clean solution would be to load the library(s) from an absolute location.

**Comment by jukzi** [comment]
see also
https://support.microsoft.com/en-us/topic/secure-loading-of-libraries-to-prevent-dll-preloading-attacks-d41303ec-0748-9211-f317-2edc819682e1
https://www.chilkatsoft.com/java-loadlibrary-windows.asp
