### ISSUE TITLE
Are all performance tests being executed?

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#433]
I was wondering how exactly are the performance tests being executed in the CI environment?

I found these CI-Jobs in the Releng Jenkins but some performance tests seem to be missing (i.e. they are not running)
* Jenkins: https://ci.eclipse.org/releng/job/PerformanceTests/
* Some (of many?) missing performance tests: all under the package `org.eclipse.core.tests.resources.content`

I am specifically interested in the tests in `org.eclipse.core.tests.resources.perf.ContentDescriptionPerformanceTest` since some of them are failing locally (see #432)

**Comment by fedejeanne** [comment]
Also, these tests don't seem to belong in this job: [org.eclipse.jdt.debug.tests](https://ci.eclipse.org/releng/job/PerformanceTests/job/ep428I-perf-lin64-baseline/lastSuccessfulBuild/testReport/org.eclipse.jdt.debug.tests/)

**Comment by jukzi** [comment]
From hearsay there once was a time when performance tests where executed on a dedicated server with reproducible timings. The server was shut down ages ago by the contributing company and no-one else contributed another test environment.

**Comment by fedejeanne** [comment]
Thank you @jukzi for answering. I'm closing this "ticket" :)
