### ISSUE TITLE
Compilation errors in platform with I20230509-1800 compiler

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#444]
With the ECJ fix for https://github.com/eclipse-jdt/eclipse.jdt.core/commit/eeef6622e4e108712c236d5ddae7e8923fc6db65 I see lot of compilation errors like `Redundant specification of type arguments` all over in the SDK workspace.

The errors **are valid** (compiler simply missed to report them before and this is fixed now) so we should make sure we fix them.

The fixes are trivial and I plan to provide PR's for them.

@jarthana: FYI.

**Comment by iloveeclipse** [comment]
I've fixed errors I saw in my workspace on Linux, there could be other in Windows/Mac specific bundles we have, so if anyone sees some remaining errors, please fix.

Note: ideally that should be done soon before we switch to the updated ECJ build in M3.

**Comment by jarthana** [comment]
Thanks Andrey for taking care of this!

**Comment by iloveeclipse** [comment]
> Thanks Andrey for taking care of this!

You are welcome Jay as long as you continue taking care of JDT :-)
