### ISSUE TITLE
[Regression] Balance text compare causes overlapping RangeDifferences

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform#458]
#323 introduced a regression:

https://github.com/eclipse-platform/eclipse.platform/pull/323/files/8a8d01488ef4cea75efb981b806fdac1f3c04a07#diff-80809369e0a624c43bbae4fa6e3aca3bfc86cb3878320f4339bc0d9e2ae2aeb2R126

`previousEnd` is never incremented and `RangeDifference`s can now overlap.

This fails, e.g. when adding all such diffs to a `MultiTextEdit`:

```java
		MultiTextEdit result = new MultiTextEdit();

		TextRangeComparator left = new TextRangeComparator(fromText, compareMode);
		TextRangeComparator right = new TextRangeComparator(toText, compareMode);

		RangeDifference[] differences = RangeDifferencer.findDifferences(left, right);
		for (RangeDifference difference : differences) {
			TextRange leftRange = left.getRange(difference.leftStart(), difference.leftLength());
			TextRange rightRange = right.getRange(difference.rightStart(), difference.rightLength());

			ReplaceEdit replaceEdit = new ReplaceEdit(leftRange.offset, leftRange.length, rightRange.text);
			result.addChild(replaceEdit);
		}
		result.apply(document);

```

```
org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)
	at java.base/java.util.Collections.indexedBinarySearch(Collections.java:336)
	at java.base/java.util.Collections.binarySearch(Collections.java:324)
	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)
	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)
	at org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)
	...
```

**Comment by iloveeclipse** [comment]
@sratz : thanks for raising the issue & I agree with revert.

**But**: could you please add your test to SDK tests, so that next time we will immediately see the problem if something changes?

**Comment by sratz** [comment]
> **But**: could you please add your test to SDK tests, so that next time we will immediately see the problem if something changes?

The test object used was an internal source code artifact (>20000 lines) that we use for such smoke tests.

I'll try to craft a minimal example that can reproduce this issue.
