### ISSUE TITLE
Move eclipse.platform.ui into this repository

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#48]
[eclipse.platform](https://github.com/eclipse-platform/eclipse.platform) already contains e.g.

- org.eclipse.e4.core.contexts
- org.eclipse.e4.core.di.annotations
- org.eclipse.e4.core.di.extensions.supplier
- org.eclipse.e4.core.di.extensions
- org.eclipse.e4.core.di
- org.eclipse.e4.core.services 

while [eclipse.platform.ui](https://github.com/eclipse-platform/eclipse.platform.ui) contains

- org.eclipse.e4.core.commands
- org.eclipse.e4.emf.xpath
- org.eclipse.e4.ui.bindings
- org.eclipse.e4.ui.css.core
- org.eclipse.e4.ui.css.swt.theme
- org.eclipse.e4.ui.css.swt
- org.eclipse.e4.ui.di
- org.eclipse.e4.ui.dialogs
- org.eclipse.e4.ui.ide
- org.eclipse.e4.ui.model.workbench
- org.eclipse.e4.ui.progress
- org.eclipse.e4.ui.services
- org.eclipse.e4.ui.swt.gtk
- org.eclipse.e4.ui.swt.win32
- org.eclipse.e4.ui.widgets
- org.eclipse.e4.ui.workbench.addons.swt
- org.eclipse.e4.ui.workbench.renderers.swt.cocoa
- org.eclipse.e4.ui.workbench.renderers.swt
- org.eclipse.e4.ui.workbench.swt
- org.eclipse.e4.ui.workbench
- org.eclipse.e4.ui.workbench3 

so booth are close related and it would ease development to merge them. Also the recent merging has not revealed any issues.

@vogella WDYT?

**Comment by mickaelistria** [comment]
See also discussions in https://github.com/eclipse-platform/eclipse.platform/issues/7 and https://github.com/eclipse-platform/eclipse.platform/issues/10

**Comment by vogella** [comment]
AFAIK the build times for platform.ui are very long so this would make the validation time too long. We have other repos still be move once this is done, we can reconsider.

**Comment by laeubi** [comment]
I just checked the Jenkins and it seems most time is taken by the tests, we probably should check ways to improve the time here, e.g by allowing to execute them in parallel?

**Comment by vogella** [comment]
Sure, once the verfication build is faster, we can reconsider. Even without a repo merge having the build faster is always desirable.
