### ISSUE TITLE
Move eclipse.platform.common to this repository

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#49]
https://github.com/eclipse-platform/eclipse.platform.common could be moved here, it seems there is neither much content not much activity in this repository and as it is "common" to platform ...

@vogella WDYT?

**Comment by mickaelistria** [comment]
See also discussions in https://github.com/eclipse-platform/eclipse.platform/issues/7 and https://github.com/eclipse-platform/eclipse.platform/issues/10

**Comment by vogella** [comment]
+1 from my side. Any concerns @akurtakov?

**Comment by akurtakov** [comment]
Only concern is that eclipse.platform.common bundles do not build correct with -Pbuild-individual-bundles so one would have to find how to exclude them from verification build for eclipse.platform repository. Note: there currently is no verification build eclipse.platform.common.

**Comment by laeubi** [comment]
> Only concern is that eclipse.platform.common bundles do not build correct with -Pbuild-individual-bundles

Is there a special reason/issue why this do not work?

**Comment by akurtakov** [comment]
It relies on all other repos to be checked out in specific path so it generates javadoc based on these paths.

**Comment by laeubi** [comment]
So actually it is not "common" code but creates javadoc bundles? Help content? Something else?

**Comment by akurtakov** [comment]
It's only help content. AFAICT (this has been done ages ago before me) it's "common" repo for platform, pde,jdt, equinox subprojects  DOCUMENTATION and contains no code at all but rather generated javadocs, extension points documentation, other manually written help

**Comment by merks** [comment]
Indeed, moving these cross organization (Platform, PDE,, JDT) **doc** bundles into eclipse.platform make no sense.

![image](https://user-images.githubusercontent.com/208716/182803289-9fbadfa5-d45d-4165-9d1d-aa6e7408e8b2.png)

Don't do it.  🥲

**Comment by laeubi** [comment]
Okay close it then, there are more valuable things to merge first then.
