### ISSUE TITLE
Show number of differences in the Compare editor

### ISSUE THREAD

**Issue by pbodnar** [eclipse-platform/eclipse.platform#504]
Anyone who have ever tried to count all the change markers of the Compare editor for a large file, will probably say it might be quite a lengthy procedure.

So it would be pretty handy to have the number of differences explicitly displayed when comparing files in the Compare editor. IntelliJ IDEA has got this for years already - see for example their screenshot at https://www.jetbrains.com/help/idea/comparing-files-and-folders.html#comparing_files.

It is probably for a discussion where exactly to place that  `# difference(s)` label. Some Compare editor related data are already displayed down in the workbench status bar, but this is quite far from where users will typically be looking at?

**Comment by mickaelistria** [comment]
On the top of the compare editor, just above the text viewer, I see "Text Compare". I imagine the amount of difference could be prompted here: "Text compare: 12 different blocks, 123 lines". However, I suspect this would be per "compare" starategy (ie how you count differences in Text Compare is not how you'd count difference in some Java compare where one would care about eg "1 field with different name, 1 method returning different type...." and this kind of AST-oriented information.

**Comment by pbodnar** [comment]
@mickaelistria, thanks for the suggestions. So what about displaying just the number of differences (or "different blocks", as you suggest) for the beginning?

I guess this could work regardless of concrete compare strategy (e.g. Java Structure Compare) - the number of differences only for the currently displayed "structured block" would be displayed as illustrated on this picture:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/12137106/903c8ad7-44b9-4467-811d-55ab1a58c8af)

**Comment by mickaelistria** [comment]
Yes, just mentioning "differences" and let the compare strategy decide of what it calls a difference (ie a block of text, an AST element...) would probably be best.

**Comment by pbodnar** [comment]
Yes, and I think it would be ideal if the number displayed would simply match the number of "change markers" next to the scrollbar.

**Comment by lathapatil** [comment]
https://github.com/eclipse-platform/eclipse.platform/assets/130035155/b6276506-057e-4172-817f-e21edef644a9

Refer the attached video for this enhancement which shows the differences in compare editor. Let me know if this is fine to go ahead with PR?

**Comment by mickaelistria** [comment]
This proposal seems good to me.

**Comment by iloveeclipse** [comment]
> Let me know if this is fine to go ahead with PR?

Yes please.

**Comment by iloveeclipse** [comment]
@lathapatil : could you please add N&N entry for the change in compare editor?
It should be done in https://github.com/eclipse-platform/www.eclipse.org-eclipse repo, on this file: https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.31/platform.html

**Comment by iloveeclipse** [comment]
The new test fails on SDK build

https://download.eclipse.org/eclipse/downloads/drops4/I20231221-0400/testresults/html/org.eclipse.compare.tests_ep431I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
/labelContributionData/file1.java

java.io.FileNotFoundException: /labelContributionData/file1.java
at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
at java.base/java.net.URL.openConnection(URL.java:1094)
at java.base/java.net.URL.openStream(URL.java:1161)
at org.eclipse.compare.tests.TextMergeViewerTest.testToolbarLabelContribution(TextMergeViewerTest.java:519)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

I will push a fix.

**Comment by lathapatil** [comment]
> I will push a fix.

Thanks for the quick fix..

**Comment by iloveeclipse** [comment]
Test is fine in https://download.eclipse.org/eclipse/downloads/drops4/I20231221-1800/
