### ISSUE TITLE
"Run As" Context Menu shows Ant Run Configurations multiple times

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#527]
![image](https://github.com/eclipse-platform/eclipse.platform.debug/assets/51790620/18fb9132-ccb1-459a-a968-03a936b1c606)
example from platform worspace: /org.eclipse.jdt.ui/scripts/build_jar-in-jar-loader.xml

@mickaelistria probably caused by the changes in that menu

**Comment by jukzi** [comment]
@mickaelistria still happens
![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/119a4c7d-0957-415a-9261-79204d265984)

**Comment by sudhindrakkulkarni102** [comment]
From the above discussion I understand that the shortcuts are duplicated and only one shortcut(context menu entry highlighted in yellow) should be ideally shown. Please confirm if my understanding is correct.

**Comment by laeubi** [comment]
Yes that is correct.

**Comment by SudhindraKKulkarni** [comment]
@jukzi  Please review and confirm if the the changes in the pull request are fine.

**Comment by Bananeweizen** [comment]
I've raised #798 for another duplication of launch configs. Just saying, if someone is touching code for filtering duplicates...

**Comment by jukzi** [comment]
> Indeed. We could easily de-deduplicate results.

@mickaelistria can you please review the proposed PR, i am not into the implementation details. I only see that the change looks more complicated then an easy de-duplication.

**Comment by laeubi** [comment]
See 
- https://github.com/eclipse-platform/eclipse.platform/pull/800

for generic deduplication, but
- https://github.com/eclipse-platform/eclipse.platform/pull/730

should still be considered as it fixes the root of the problem.
