### ISSUE TITLE
[Tests] org.eclipse.debug.tests.console.ProcessConsoleTests fails with No console complete notification received.

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-platform/eclipse.platform#545]
https://download.eclipse.org/eclipse/downloads/drops4/I20220528-0600/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

testProcessTerminationNotificationWithInputFile | Failure | No console complete notification received.java.lang.AssertionError: No console complete notification received.at org.junit.Assert.fail(Assert.java:89)at org.junit.Assert.assertTrue(Assert.java:42)at org.eclipse.debug.tests.console.ProcessConsoleTests.processTerminationTest(ProcessConsoleTests.java:285)at org.eclipse.debug.tests.console.ProcessConsoleTests.testProcessTerminationNotificationWithInputFile(ProcessConsoleTests.java:250)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)
-- | -- | --

**Comment by fedejeanne** [comment]
Hi.
It is in fact a random failure but not because of a timeout (as it was suggested in #548).

See [comment](https://github.com/eclipse-platform/eclipse.platform/issues/548#issuecomment-1620365593) and also #563.

Hope this helps :-)

**Comment by HeikoKlare** [comment]
This is a duplicate of #548
