### ISSUE TITLE
Performance E4 Injector

### ISSUE THREAD

**Issue by N1k145** [eclipse-platform/eclipse.platform#576]
We have a case where we have around 400k Injected Objects in one of the _injectedObjects_ lists in the E4 Injector.

Injecting those takes about 500 seconds, which is way too long. The main time is lost iterating the list of injected objects and checking if the object is already contained.

**Comment by merks** [comment]
@N1k145 

Thanks for the improvement and for being so receptive to suggestions.

**Comment by N1k145** [comment]
@merks Thank you for the in-depth review and the suggestions.
