### ISSUE TITLE
failing Test PrebuiltIndexCompatibility.test9_4_2LuceneCompatible

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#601]
on all platforms in i-build since I20230726-0640:

https://download.eclipse.org/eclipse/downloads/drops4/I20230726-0640/testresults/html/org.eclipse.ua.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20230726-0640/testresults/html/org.eclipse.ua.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20230726-0640/testresults/html/org.eclipse.ua.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20230726-0640/testresults/html/org.eclipse.ua.tests_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html

**Comment by merks** [comment]
There is PR open regarding that issue:

https://github.com/eclipse-platform/eclipse.platform/pull/595

I personally think it's useless to have a test method that tests only if the hard-coded version in that method is equal to the hard-coded version in the target platform.  That's just a maintenance problem, not a test...
