### ISSUE TITLE
Random failing ParallelBuildChainTest.testWorkspaceParrallelBuildNoConflict

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#609]
The test case `org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testWorkspaceParrallelBuildNoConflict` randomly fails:
https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-606/3/testReport/

```
org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testWorkspaceParrallelBuildNoConflict -- Time elapsed: 5.781 s <<< FAILURE!
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:200)
	at org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testWorkspaceParrallelBuildNoConflict(ParallelBuildChainTest.java:210)
```

Maybe this is only is matter of slow execution, since according to the asserted states the tested build operation seems to have finished properly but only took too long.

**Comment by mickaelistria** [comment]
Can you reproduce it locally?

**Comment by HeikoKlare** [comment]
At least on my machine, it's possible to enforce the failure by adding a sleep of 2 seconds to the `run` operation of the job that is spawned within the test. Reason: The long running builds run for 1 second and adding 2 seconds makes the condition (3 times the duration of long running builds = 3 seconds) fail, while the `join` call to the job is still successful (5 seconds timeout).

I am not sure whether that emulates a timing behavior that is the cause for the random failues in CI builds, but it is at least one possibility.

My understanding is that the test is only supposed to validate that multiple build operations with non-conflicting scheduling rules can run in parallel. There already is an explicit builder for emulation (`TimerBuilder`). It would make much more sense to have this builder run indefinitely and await that builders for all projects are spawned in parallel. Then the builds can be cancelled again. This would be (1) deterministic independent of the executing hardware and (2) much more efficient than the busy waiting that is currently implemented.

If no one else is interested, I will work on a PR providing that improvement as soon as possible.

**Comment by mickaelistria** [comment]
> My understanding is that the test is only supposed to validate that multiple build operations with non-conflicting scheduling rules can run in parallel. 

Yes.

> It would make much more sense to have this builder run indefinitely and await that builders for all projects are spawned in parallel

Good idea. Feel free to improve tests that way.
