### ISSUE TITLE
buildJSPs.xml fails to run in IDE

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#612]
![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/76cfdbdb-66dd-4a11-b470-09285eb8a956)

```
BUILD FAILED
C:\Users\jkubitz\platform-2023-08-02\git\eclipse.platform\ua\org.eclipse.help.webapp\buildJSPs.xml:54: The following error occurred while executing this line:
C:\Users\jkubitz\platform-2023-08-02\git\eclipse.platform\ua\org.eclipse.help.webapp\buildJSPs.xml:70: C:\Users\jkubitz\platform-2023-08-02\ws\.metadata\.plugins\org.eclipse.pde.core\.install_folders\1690954063484\plugins does not exist.

```
eclipse.buildId=4.29.0.I20230801-1800
java.version=17.0.8

**Comment by jukzi** [comment]
i haven't seen this failure in the past. @laeubi you have been the last to touch this

**Comment by laeubi** [comment]
I'm not aware ever touching `buildJSPs.xml`, it might be that I'm in the list because I merged the repositories but I have no clue what this does and the error seem to indicate something in your eclipse install.

**Comment by mickaelistria** [comment]
cc @akurtakov do you have a clue?

**Comment by akurtakov** [comment]
IMHO it's time to stop compilation of jsps in the ide nowadays.

**Comment by merks** [comment]
I was playing with it recently when trying to understand how to get this to work with newer libraries.  I never could figure out where ${target_home} is supposed to be located, but this list of jars looks to be kind of unmaintainable.  I have no idea why these things need to be pre-compiled in the first place.  Surely the Tycho build is not pre-compiling is it?

**Comment by laeubi** [comment]
`${target_home}` is the location of the current selected target see:
https://github.com/eclipse-pde/eclipse.pde/issues/169

**Comment by laeubi** [comment]
> That's what I figured, but I don't think all the jars that are needed are actually necessarily located there

Sure this is just working "accidentally" for some time where this resolved to the bundlepool, but maven do not use the bundle-pool but the maven local repository.

**Comment by merks** [comment]
Does the platform's maven build for this bundle run the ant task?  

Note that it (the ant script) expects there to be a plugins folder and that all the jars are in that folder:
```
			<fileset dir="${target_home}/plugins">
				<patternset>
					<include name="jakarta.servlet*.jar"/>
					<include name="javax.servlet.jsp*.jar"/>
					<include name="javax.el*.jar"/>
					<include name="com.sun.el*.jar"/>
					<include name="org.apache.ant*/lib/ant.jar"/>
					<include name="org.apache.commons.logging*.jar"/>
					<include name="org.apache.jasper.glassfish*.jar"/>
					<include name="org.eclipse.core.runtime*.jar"/>
					<include name="org.eclipse.osgi*.jar"/>
					<include name="org.eclipse.help*.jar"/>
					<include name="org.eclipse.help.base*.jar"/>
				</patternset>
			</fileset>
```
I'm a little doubtful that anything meets that assumption...

**Comment by akurtakov** [comment]
Maven build uses jetty-jspc-maven-plugin to verify jsps compile proper as configured at https://github.com/eclipse-platform/eclipse.platform/blob/master/ua/org.eclipse.help.webapp/pom.xml#L27 . Thus buildJSPs.xml is(was TBH) used only for verification in the IDE which doesn't make much sense and probably m2e can handle this proper (I haven't tried) thus buildJSPs.xml is irrelevant and only effort I can justify spending on it is deleting it.
