### ISSUE TITLE
Directories in ISO Charset not shown in Project explorer/Java 19 issue

### ISSUE THREAD

**Issue by mrhaarmann** [eclipse-platform/eclipse.platform#642]
We are running Eclipse IDE version 2023-06 in two different environments, since one older project requires ISO-8859-15 locale.
(in Linux version)
In order to achieve this, we are starting eclipse with a number of environment settings:
export LANG=de_DE@euro
export LANGUAGE=de_DE:de:en_GB:en
export LANG=de_DE@euro
export LC_ALL=de_DE@euro
export GDM_LANG=de_DE@euro
export LC_NAME=de_DE@euro
export LC_MONETARY=de_DE@euro
export LC_MEASUREMENT=de_DE@euro
export LC_TELEPHONE=de_DE@euro
export LC_PAPER=de_DE@euro
export LC_IDENTIFICATION=de_DE@euro
export LC_TIME=de_DE@euro
export LC_NUMERIC=de_DE@euro
export LC_ADDRESS=de_DE@euro
This will lead to filenames with ISO-8859-15 encoding and also content in ISO-8859-15 encoding, when the workspace is set to encoding from environment.
We recently tried to execute Eclipse with Java 19 instead of the Java 17 version and found an issue which might be addressed by the platform.
When eclipse is started in 8859-15 locale, directory names which contain german Umlaut characters (such as äöü) are not displayed any more in the Project explorer (when refreshing the list). Even new directories are created correctly (on the filesystem, everything looks hood) and vanish from view when a refresh is done.
This can also be reproduced with Eclipse 2023-03, running with Java 19.
The JDT people told me they rely on the underlying platform code, so thats why I open an issue here.
For the meantime, we are running with Java 17, but at some point in the future, an upgrade will be needed.

**Comment by merks** [comment]
@iloveeclipse   You're awesome!  🥇

**Comment by iloveeclipse** [comment]
> Since the issue has been found probably, when will a night build be available so we can test this ?

Not until 4.29. The change https://github.com/eclipse-platform/eclipse.platform/pull/643 touches the very basic part of file system access in Eclipse, and even if I see that it might fix your issue, I fear it might also cause unexpected side effects for others. We are in 4.29 RC1 phase now and such changes can only be made in M1/M2.

What you are welcome to do is to test the change by locally building SDK with the patch applied.

**Comment by mrhaarmann** [comment]
Completely understood, we can deal with that. As I mentioned earlier, this was just a test run with java 19. 
We do not rely on a Java 19 runtime at the moment.
We are able to work with java 17 for some time until this gets released.
I will try to find some time to compile the SDK, but this is not within the next days.

**Comment by iloveeclipse** [comment]
@mrhaarmann : please try tomorrow's nightly SDK build from https://download.eclipse.org/eclipse/downloads/.

**Comment by mrhaarmann** [comment]
I tried the night build from wednesday and the described effect 
of the directory name with ISO charset is displayed correctly now in project explorer, refresh works as expected.
(in java17 and java19, did not try newer versions).
Thank you for your help.

**Comment by iloveeclipse** [comment]
@mrhaarmann: thanks for validation!
