### ISSUE TITLE
Console Scroll Lock is disabled with key "End"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#648]
I understand that the key combination ctrl+end (i.e. document end) may make sense to disable scroll lock, but only the key end (line end) in the middle of the console shout not disable scroll lock
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/933c223a-90ec-4cb1-b28d-59df5bd4a2b4)

**Comment by HeikoKlare** [comment]
fixed via #649
