### ISSUE TITLE
Failure of test org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.testPlatformIsvStatic

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#668]
Failed in [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/6121624211/job/16615790108?pr=666#step:7:16243) of https://github.com/eclipse-platform/eclipse.platform/pull/666

```java
org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.testPlatformIsvStatic -- Time elapsed: 0.143 s <<< FAILURE!
java.lang.AssertionError: 
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/eclipse_4_29_porting_guide.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/faq.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/incompatibilities.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/recommended.html

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.doAssert(TocLinkChecker.java:129)
	at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.testPlatformIsvStatic(TocLinkChecker.java:84)
```

**Comment by akurtakov** [comment]
This should be fixed (via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/fb48617de266ff5fc19a8921c9ebd2f0e53cf767 ) . Let's see tomorrow's I-build.

**Comment by HeikoKlare** [comment]
As far as I can see, the porting information has only been merged into the `R4_29_maintenance` branch but not into `master`: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1290

Maybe that's the reason why they are missing?

**Comment by akurtakov** [comment]
Isn't https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/c5892bd1d67d98adc0c7c6d387be9d540c2a3ca1 the patch to master?

**Comment by HeikoKlare** [comment]
It is, but I think in that one the porting files for platform were missing (by accident) and were thus added with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1290 that has only been merged to the maintenance branch for 4.29.

The 4.29 porting files for platform are actually missing on master and GitHub also states that the maintenance branch is ahead of master with the commit including those files.

**Comment by akurtakov** [comment]
Ah, I would appreciate if someone pushes the missing files to master.

**Comment by HeikoKlare** [comment]
I've created a PR with the according commit against master: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1335

**Comment by HeikoKlare** [comment]
Files are in master now. Let's recheck tomorrow if tests succeed again.

**Comment by HeikoKlare** [comment]
Fixed via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1335.

I-build tests succeeded last night again, e.g., https://download.eclipse.org/eclipse/downloads/drops4/I20230911-1800/testresults/html/org.eclipse.ua.tests.doc_ep430I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

GH actions builds succeed again as well, e.g., https://github.com/eclipse-platform/eclipse.platform/actions/runs/6155481695
