### ISSUE TITLE
Toggle revision information

### ISSUE THREAD

**Issue by moabson** [eclipse-platform/eclipse.platform#67]
Currently, I can't find a way to quickly toggle revision information (git blame) through a shortcut. I can put a shortcut to display revision information but I can't do the same to hide it.

![image](https://user-images.githubusercontent.com/2575708/167896845-568814b0-44c7-4dfc-9b0f-c3480be61cef.png)

**Comment by mickaelistria** [comment]
Unfortunately, I think this "toggle" command is missing and there is no way to hide revision information. @moabson  Would you be interesting is trying to contribute such a command?

**Comment by merks** [comment]
Yes, even in the menu one would expect it to be a checked menu item but instead there are two menu items:

![image](https://user-images.githubusercontent.com/208716/183047016-1438ccac-ddd8-4e86-8cba-42f91560d8f6.png)

Doesn't this this comes from EGit rather than the platform?

**Comment by mickaelistria** [comment]
@merks you're right, the command is `org.eclipse.egit.ui.team.ShowBlame`, so it's EGit only (not sure whether this would be worth having this a common feature of Platform's team framework, but that's only topic).
@moabson Can you please report this issue to EGit project then.
I'm closing it here as at the moment, Platform is not the place where this can be fixed.

**Comment by merks** [comment]
You can report a bug here:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit
