### ISSUE TITLE
failing linkchecker.ApiDocTest.testTopicsReference

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#682]
ApiDocTest.testTopicsReference fails i-build I20230913-1800
foer example:
https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/testresults/html/org.eclipse.ua.tests.doc_ep430I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
expected:<[]> but was:<[ * Unexpected extension points in topics_Reference.xml: org.eclipse.search.textSearchEngine ]>

org.junit.ComparisonFailure: expected:<[]> but was:<[
* Unexpected extension points in topics_Reference.xml:
org.eclipse.search.textSearchEngine
]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.ua.tests.doc.internal.linkchecker.ApiDocTest.testTopicsReference(ApiDocTest.java:181)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by iloveeclipse** [comment]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1105.

@mickaelistria : could you please take a look?

**Comment by iloveeclipse** [comment]
Also note [comment](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349#issuecomment-1719004119) from @akurtakov regarding failing releng test:

> It's in the https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/logs.php#javadoc . https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/compilelogs/platform.doc.isv.javadoc.txt points that first failure is due to search.[core/ui] split and not being added to javadoc build.
