### ISSUE TITLE
Migrate to org.apache.ant 1.10.14

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform#701]
Orbit is preparing a new version of ant using newer infrastructure:

https://github.com/eclipse-orbit/orbit-simrel/issues/13

There is one minor incompatibility caused by the introduction of org.apache.tools.ant.BuildLogger.getMessageOutputLevel()
```
    /**
     * @return Returns the {@link #setMessageOutputLevel(int) currently set} message output level.
     * The {@code default} implementation of this method returns {@code MSG_INFO}.
     * @since 1.10.13
     */
    default int getMessageOutputLevel() {
        return Project.MSG_INFO;
    }
```
The protected method in org.eclipse.ant.internal.launching.runtime.logger.NullBuildLogger.getMessageOutputLevel() and org.eclipse.ant.tests.core.support.testloggers.TestBuildLogger.getMessageOutputLevel() "override" this with **protected** methods, causing a compile error.

Migration to new versions in general is difficult because the org.apache.ant version is hard coded in the tests.  The target platform is in a different git repository making it a challenge to update both the hard-coded version and the version in the target platform at the same time.  Better would be to compute the version from the available org.apache.ant bundle.

**Comment by iloveeclipse** [comment]
@merks : what is the state of this issue?

**Comment by merks** [comment]
The status is that I need to get SimRel builds working after the migration to here:

https://github.com/eclipse-simrel

The Orbit changes for this Ant version are basically ready, but I need to set up the ci build for it.  As you can see, I've already tested locally that the Ant tests run, so I think there will be no roadblocks...

ETA is likely some time this weekend...

**Comment by merks** [comment]
The target platform updates are in progress here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1387
