### ISSUE TITLE
Lots of extracted plug-ins in an Eclipse installlation 

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform#722]
Today I downloaded Eclipse for Windows and extracted the zip file. It took very long (as Windows filesystem is so slow) and I noticed that it had to write > 15 000 files. One of the reasons seems to be that lots of plug-ins are not delivered as JAR but extracted, e.g. the EPP stuff seems to get extracted.

Is this necessary or just "the way we did it in the past"? Using more JARs files instead of extraced content would reduce the file system operations for download, extraction and copy of Eclipse installation

cc @merks @jonahgraham WDYT?

**Comment by akurtakov** [comment]
Would you please provide a list of extracted bundles ?

**Comment by iloveeclipse** [comment]
Please define "a lot".
The Friday's build on Linux I see only following directories extracted, the rest are jars:
```
eclipse4.30/eclipse/plugins/com.sun.jna_5.13.0.v20230812-1000
eclipse4.30/eclipse/plugins/org.apache.ant_1.10.12.v20211102-1452
eclipse4.30/eclipse/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024
eclipse4.30/eclipse/plugins/org.eclipse.equinox.security.linux_1.1.0.v20230630-1303
eclipse4.30/eclipse/plugins/org.eclipse.jdt.debug_3.21.200.v20230920-0547
eclipse4.30/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230913-0815
eclipse4.30/eclipse/plugins/org.eclipse.platform_4.30.0.v20230922-0140
eclipse4.30/eclipse/plugins/org.eclipse.sdk_4.30.0.v20230922-0140
eclipse4.30/eclipse/plugins/org.eclipse.ui.themes_1.2.2300.v20230807-1354
```

**Comment by merks** [comment]
I'm pretty sure these are necessary.  E.g., when there are nested libraries/jars, they will necessarily be unpacked somewhere....

**Comment by laeubi** [comment]
@vogella I think it would even be great to have only one big Exe/Zip/Jar/... and Eclipse would extract everything on first startup (not that it would be faster) as Windows is a PITA when it comes to extracting Eclipse (e.g. default zip tool fails on long path used in standard eclipse).

**Comment by laeubi** [comment]
> Please define "a lot".
> The Friday's build on Linux I see only following directories extracted, the rest are jars:

The point is not the number of _folders_ but the number of _files_ contained *inside* the folders.

**Comment by iloveeclipse** [comment]
> The point is not the number of _folders_ but the number of _files_ contained _inside_ the folders.

420 files.

**Comment by merks** [comment]
If one uses the installer, all the common files and folders are shared in the bundle pool across any number of installations:
```
merks@CORE MINGW64 /d/Users/merks/platform-sdk-4.30/eclipse/plugins
$ls -sailR
.:
total 60
 562949973808760  0 drwxr-xr-x 1 merks 197609     0 Sep 13 10:14 ./
9288674233512303  4 drwxr-xr-x 1 merks 197609     0 Sep 20 14:07 ../
 562949973808761 56 -rw-r--r-- 1 merks 197609 55877 Sep 13 10:14 org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
```

**Comment by vogella** [comment]
> Please define "a lot". The Friday's build on Linux I see only following directories extracted, the rest are jars:
> 
> ```
> eclipse4.30/eclipse/plugins/com.sun.jna_5.13.0.v20230812-1000
> eclipse4.30/eclipse/plugins/org.apache.ant_1.10.12.v20211102-1452
> eclipse4.30/eclipse/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024
> eclipse4.30/eclipse/plugins/org.eclipse.equinox.security.linux_1.1.0.v20230630-1303
> eclipse4.30/eclipse/plugins/org.eclipse.jdt.debug_3.21.200.v20230920-0547
> eclipse4.30/eclipse/plugins/org.eclipse.pde.build_3.12.200.v20230913-0815
> eclipse4.30/eclipse/plugins/org.eclipse.platform_4.30.0.v20230922-0140
> eclipse4.30/eclipse/plugins/org.eclipse.sdk_4.30.0.v20230922-0140
> eclipse4.30/eclipse/plugins/org.eclipse.ui.themes_1.2.2300.v20230807-1354
> ```

I used the EPP download

**Comment by jonahgraham** [comment]
Which EPP? And which bundles? Afaik there are lots of extracted bundles for lsp related stuff, such as language servers from wwd.

**Comment by vogella** [comment]
> Which EPP? And which bundles? Afaik there are lots of extracted bundles for lsp related stuff, such as language servers from wwd.

I downloaded the zip for committer, but at the moment working with a client on Linux, I can check later why the zip tool told me that it extracts > 15 000 files. Just for reference I did not counted it but I started the extraction and had breakfast, after breakfast the unzipping was still running so I guess extraction took longer than 10 mins.

**Comment by jonahgraham** [comment]
Most likely this bug needs redirecting at the projects producing the extracted bundles (or Microsoft for having such a shockingly show zip program by default!). I look forward to your analysis when you get a chance.

**Comment by Bananeweizen** [comment]
NTFS is not thaaaat slow. My 8 year old Windows desktop is done in about 40 seconds. Use 7zip and check if that customer uses a typical business virus scanner. Those often intercept every file access fully until they have analyzed the file being accessed entirely. I've seen that lead to a slowdown of factor 10 to 20 in my company, too. The files are from wildwebdeveloper, with a complete Node installation and stuff like that inside.

Sorry for the German screenshots, but the numbers and other highlights should be pretty clear.
![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/406876/159c26db-beb6-47a8-af8e-dd58c8e177c3)
![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/406876/f3799e39-e7f5-4ab7-b92c-86ad05c161bb)

**Comment by jukzi** [comment]
only wildwebdeveloper to blame:
https://ftp.fau.de/eclipse/technology/epp/downloads/release/2023-09/R/eclipse-committers-2023-09-R-win32-x86_64.zip

![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/dce4f8ac-c951-47d0-acd7-83729a0d132b)

**Comment by jukzi** [comment]
closed as not platform.
