### ISSUE TITLE
Remove recycling of ThreadJob in ImplicitJobs

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#724]
The `JobManager` uses the `ImplicitJobs` implementation to spawn internal jobs for the execution on a specific `ISchedulingRule` within an executed job:

https://github.com/eclipse-platform/eclipse.platform/blob/ca35cee037256b0f6213f84acbf9de28a9650431/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/JobManager.java#L340-L343

This implementation creates instances of `ThreadJob`. These instances are reused, such that the same `ThreadJob` instance is reused for different rules and potentially different jobs. 
_Side note_: Reusing the same `ThreadJob` within the same job for a different rule already led to race conditions (see #659).
This is achieved by a _recycle_ functionality, which caches a `ThreadJob` for reuse once it is not used anymore:

https://github.com/eclipse-platform/eclipse.platform/blob/ca35cee037256b0f6213f84acbf9de28a9650431/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/ImplicitJobs.java#L225-L228

https://github.com/eclipse-platform/eclipse.platform/blob/ca35cee037256b0f6213f84acbf9de28a9650431/runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/ImplicitJobs.java#L195-L208

This functionality results in the same job occuring with different rules at different places and points in time. This is both unexpected and error prone (as can be see in issue #659).

In addition, the recycling functionality exists since the early days of Eclipse. At that time, this may have been a useful performance improvement, while I don't expect this to still be relevant nowadays.

Referring to https://github.com/eclipse-platform/eclipse.platform/pull/661#discussion_r1339883084, I propose to remove this recycling functionality to reduce code complexity and avoid the unnecessary risk of errors.

**Comment by iloveeclipse** [comment]
> the recycling functionality exists since the early days of Eclipse. At that time, this may have been a useful performance improvement, while I don't expect this to still be relevant nowadays.

I also don't see immediately what could be a good reason for recycling. 
Creating new ThreadJob shouldn't cost much time looking on the code, reusing however involves central JobManager locks.

Just wondering if there is some use case with high frequency creation of ThreadJob objects that can make GC life harder as it should be.

> I propose to remove this recycling functionality to reduce code complexity and avoid the unnecessary risk of errors.

Yes, agree, please proceed in M2, would be interesting to see if there is any side effect during M2.

**Comment by HeikoKlare** [comment]
> Just wondering if there is some use case with high frequency creation of ThreadJob objects that can make GC life harder as it should be.

Yes, that's a valid point. In such a case, additional object creation and GC work could make up a relevant overhead. However, the ThreadJobs are created when acquiring a scheduling rule, which has quite some functionality executed around it. I would expect that to produce much more overhead than the recreation of a ThreadJob. But that's only my expectation/guess.
