### ISSUE TITLE
Java Flight Recorder support for core.di @Inject calls (discuss)

### ISSUE THREAD

**Issue by col-panic** [eclipse-platform/eclipse.platform#734]
We have an Eclipse RCP application, where several @Inject calls happen on each view. 
Now I want to performance analyze the time it takes to handle these calls, and thus the
overall time until all are handled.

I did find the specific call in `org.eclipse.e4.core.internal.di.MethodRequestor#execute`
searching for an Event or other _Hook_ to use to add JFR Logging.  Now I didn't find something
and started to crudely modify and overwrite the plugin locally.

Now the general topic:

Would there be support for adding some kind of opt-in performance measurement hook
at this place? Like an e4 event or a JFR implementation at this point? The goal is, as described above,
to be able to trace the calls and the time they need on the resp. "inject endpoint" to be handled.

At the momentan I do simply something like this ... but to clearify the point:

![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/1679857/5a3b871a-6923-446e-9159-ce2cf3236078)

**Comment by laeubi** [comment]
@col-panic I think @jukzi has added some JFR already at some places and as you have the code changes already at hand it might be the besto to simply open a PR and see what happens :-)

**Comment by laeubi** [comment]
I only rember there was some effort in the old gerrit, but not sure if it ever was merged (can't find any reference to jdk.jfr in the platform code) see for example here:

- https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/189333
- https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/189308
- https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/189305

**Comment by col-panic** [comment]
After having a quick look at your zip file, I adopted the namespace and made a PR that
seems to fit for my scenario - as a base for discussion https://github.com/eclipse-platform/eclipse.platform/pull/736/files

I like this issue to https://bugs.eclipse.org/bugs/show_bug.cgi?id=578055

**Comment by jukzi** [comment]
We do not use JFR Events because 

-  a bug in jdk that they can terminate the the jvm 
-  a bug in tycho which does not complie them correctly 
-  sampling/profiling is sufficient in most cases - for example with visualvm

**Comment by col-panic** [comment]
@jukzi ok - so considering my scenario, could you give me a hint on how to alternatively measure the time @Inject operations take? Another use case would be to measure the @Activate time for an Osgi service.

**Comment by laeubi** [comment]
> a bug in tycho which does not complie them correctly

As long as there is no [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue there is no bug in Tycho ;-)

**Comment by col-panic** [comment]
pity ...
