### ISSUE TITLE
NotificationBuilder API does not allow to position the notification on the bottom of the Shell

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform#740]
In https://git.eclipse.org/r/c/platform/eclipse.platform.ui/+/183888 @marcushoepfner created a very nice builder API for notifications. AFAICS we do not have the option to tell the notification where it should be placed. In my example usage it pops up in the middle of the screen.

@marcushoepfner did I oversee something? Or was that not implemented? If not implemented do you remember why you / we did not do that?

**Comment by vogella** [comment]
Note: It looks like the new builder snippets are also not added to the JFace Snippet page, https://wiki.eclipse.org/JFaceSnippets. We should do this and potentially migrate this page to source control as the wiki will disagree soon.

**Comment by marcushoepfner** [comment]
> In https://git.eclipse.org/r/c/platform/eclipse.platform.ui/+/183888 @marcushoepfner created a very nice builder API for notifications. AFAICS we do not have the option to tell the notification where it should be placed. In my example usage it pops up in the middle of the screen.
> 
> @marcushoepfner did I oversee something? Or was that not implemented? If not implemented do you remember why you / we did not do that?

I don't see this possibility in the NotificationPopup itself. Guess that's why it is not part of the builder.

**Comment by vogella** [comment]
> I don't see this possibility in the NotificationPopup itself. Guess that's why it is not part of the builder.

I assume if we could add the shell in the builder API, it would this one as reference. For example, https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.ui/master/examples/org.eclipse.jface.snippets/Eclipse%20JFace%20Snippets/org/eclipse/jface/snippets/dialogs/Snippet081AbstractNotificationPopup.java opens up for me in the right bottom corner. Would be nice to have this also for the builder api.

**Comment by marcushoepfner** [comment]
closing this one. recreated in [platform.ui](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1226)
