### ISSUE TITLE
Tests do no clean up upon exception in setUp()

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#742]
## Current Situation

If a `setUp()` method of any JUnit 3 test class, i.e., one extending `TestCase` throws an exception, `tearDown()` will not be called. This is by design, as the [`runBare()` method](https://github.com/junit-team/junit4/blob/main/src/main/java/junit/framework/TestCase.java#L138-L153) executes the `setUp()` method outside of the try block that ensures that `tearDown()` is still called upon exceptions during execution of the actual test method.

Several platform tests are still based on JUnit 3 by extending the `CoreTest` class, which is a sublass of `TestCase` and are thus affected by potentially missing cleanup. This breaks test isolation and since all tests of one plug-in are executed on the same workspace, tests executed subsequently to one that failed during `setUp()` will face an unexpected workspace state, making test results unreliable.

## Reproduction

If you want, you can easily reproduce the behavior:

```java
public class DemoTest extends CoreTest {
	@Override
	protected void setUp() throws Exception {
		throw new IllegalStateException();
	}

	public void test() {
		//
	}

	@Override
	protected void tearDown() throws Exception {
		System.out.println("I was called");
	}
}
```

## Proposal

Until all affected test class are migrated to JUnit 4 / 5 (which ensure that @After methods [are always called, even if @Before methods throw an exception](https://junit.org/junit4/javadoc/4.12/org/junit/After.html)), I propose to adapt the behavior of the `CoreTest` class to call `setUp()` within the try block to improve test isolation by re-implementing the `runBare()` method.

**Comment by vogella** [comment]
+1 to the proposal

Heiko Klare ***@***.***> schrieb am Fr., 13. Okt. 2023, 12:42:

**Comment by HeikoKlare** [comment]
Since not all remaining JUnit 3 tests are subclasses of `CoreTest`, I will first try to migrate as many tests as possible to JUnit 4. I hope that most of the remaining JUnit 3 tests then extend `CoreTest`, such that they are affected by the workaround.

I will provide a PR as soon as I have taken a look at all remaining JUnit 3 tests for the possibility of an easy migration to JUnit 4.

**Comment by HeikoKlare** [comment]
Since now all specializations of `CoreTest` have been migrated to JUnit 4 or otherwise now specialize the general `TestCase` if they are still part of a framework relying on JUnit 3 (such as the session tests), it is not necessary anymore to improve the cleanup in the `CoreTest` class.

Instead, I propose to completely deprecate the `CoreTest` class for removal, so that no one implements it by accident. The class is tighly integrated into the JUnit 3 structure and should never be extended in new code. I have provided #1042 for the deprecation.

**Comment by HeikoKlare** [comment]
`CoreTest` has been readded via revert in #1059
