### ISSUE TITLE
regression LogSerializationTest fails on all builds

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#768]
see for example https://github.com/eclipse-platform/eclipse.platform/pull/763

locally i can not reprodcue - did something change in the build process? @laeubi ?

**Comment by jukzi** [comment]
fails on master since https://github.com/eclipse-platform/eclipse.platform/actions/runs/6637140498
https://github.com/eclipse-platform/eclipse.platform/commit/bf8985956b3e578cdb845a811971e7adebfb5f06
@iloveeclipse

**Comment by iloveeclipse** [comment]
I've reverted offending equinox change, see https://github.com/eclipse-equinox/equinox/pull/388.
On next SDK build test should work again.
