### ISSUE TITLE
Project 'External Plug-in Libraries' has no explicit encoding set

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform#85]
In my runtime workspace I see the following warning if I generated a new plug-in project.

Description	Resource	Path	Location	Type
Project 'External Plug-in Libraries' has no explicit encoding set	External Plug-in Libraries		/External Plug-in Libraries	No explicit project encoding

![image](https://user-images.githubusercontent.com/139910/174805774-c0fe2e94-a842-4a32-b6f1-39e2ad676024.png)

As this project is generated, we should not show this warning or generate the project with this new setting.

cc @iloveeclipse

**Comment by mickaelistria** [comment]
This project is created by PDE in SearchablePluginsManager , transferring to PDE for proper setting of encoding.

**Comment by mickaelistria** [comment]
Actually, we cannot transfer to PDE, so let's close it here and people who have further interest should report it to PDE.
