### ISSUE TITLE
merging repository Working Sets 

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#850]
Since merging the repositories the predefined Workingsets in platform workspace do not correspond to the repository anymore. Is that intended? I would prefer to have a workingset per repository
![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/2e52a1a2-02cc-4322-b0bd-09a6d003a3ff)

@vogella @laeubi @merks

**Comment by Bananeweizen** [comment]
But that would mean just smashing everythign of the above into one working set, or am I getting it wrong? Are you aware that you can easily add your own Working Sets via Window > Preferneces > Oomph > Working Sets, and that your own working sets will remain untouched even by Oomph setup changes?

**Comment by merks** [comment]
Yes, from my point of view its intended.  These are functional groupings of closely related bundles/tests.

**Comment by jukzi** [comment]
ok, then we leave it as is. @Bananeweizen @merks thanks for feedback.
