### ISSUE TITLE
Refresh in project explorer disabled if closed projects are included in the selection

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform#876]
If you select all entries in the project explorer to refresh them, the refresh button is not shown if one or more of these projects are closed.

That makes it harder to refresh all relevant projects.

Desired behavior: always have refresh enabled if at least one project is open and refresh all opened and selected projects.

**Comment by Dinesh0723** [comment]
The issue is reproducible in Eclipse IDE version 2022-12 (4.26.0), with build ID 20221201-1913.
