### ISSUE TITLE
Creation of milestones and releases and propagate across multiple repositories

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform#9]
Opening this issue based on https://www.eclipse.org/lists/platform-dev/msg03546.html

**Comment by sravanlakkimsetti** [comment]
related query https://www.eclipse.org/lists/platform-dev/msg03486.html

**Comment by iloveeclipse** [comment]
@SarikaSinha : do you have plans to proceed with that?
The matrix for 4.24 M1 is already incomplete...

https://bugs.eclipse.org/bugs/report.cgi?x_axis_field=product&y_axis_field=component&z_axis_field=resolution&no_redirect=1&query_format=report-table&short_desc_type=allwordssubstr&short_desc=&classification=Eclipse+Project&product=Equinox&product=JDT&product=PDE&product=Platform&longdesc_type=allwordssubstr&longdesc=&bug_file_loc_type=allwordssubstr&bug_file_loc=&status_whiteboard_type=allwordssubstr&status_whiteboard=&keywords_type=allwords&keywords=&deadlinefrom=&deadlineto=&bug_id=&bug_id_type=anyexact&votes=&votes_type=greaterthaneq&target_milestone=4.24+M1&emailtype1=substring&email1=&emailtype2=substring&email2=&emailtype3=substring&email3=&chfieldvalue=&chfieldfrom=&chfieldto=Now&j_top=AND&f1=noop&o1=noop&v1=&format=table&action=wrap

**Comment by vik-chand** [comment]
Also color/naming/description of new labels  like  'performance' , 'test' etc should be uniform across repos.

**Comment by sravanlakkimsetti** [comment]
We do have a automated way of creating milestones and labels now. Closing this

**Comment by vogella** [comment]
Can you add a noteworthy label?

**Comment by sravanlakkimsetti** [comment]
> Can you add a noteworthy label?

done

**Comment by iloveeclipse** [comment]
Can you add a regression label please? Or may be share how it can be done across all organizations?

**Comment by sravanlakkimsetti** [comment]
> Can you add a regression label please? Or may be share how it can be done across all organizations?

Because of security concerns I cannot share the job. I will quite happy to help you in this regard. Creating it now

**Comment by iloveeclipse** [comment]
Thanks Sravan, but is this somewhere documented, just in case we would need to do this again?
