### ISSUE TITLE
Support for Github Copilot

### ISSUE THREAD

**Issue by MahatmaFatalError** [eclipse-platform/eclipse.platform#948]
Are there any plans to support Github Copilot https://github.com/features/copilot ?

It would be really sad when eclipse falls behind VSCode and IntelliJ in that area. 

I think the AI topic is too important not to offer it.

**Comment by HeikoKlare** [comment]
There already is a request for an Eclipse Copilot plugin: https://github.com/orgs/community/discussions/51197

**Comment by mickaelistria** [comment]
This is out of the scope of Eclipse Platform. Eclipse Platform provides the RCP/IDE framework. GitHub copilot integration is better being a separate plugin/project. If Eclipse Platform misses features or extension point to offer decent Copilot integration, please open specific issues.
So I'm going to close it here.

However, if you're interested in starting a Copilot integration, I suspect best is to continue what has been already developed in https://github.com/masecla22/eclipse-github-copilot-integration

**Comment by vogella** [comment]
See also https://marketplace.eclipse.org/content/copilot4eclipse
