### ISSUE TITLE
Refresh job should show up in progress view for long-running tasks

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform#953]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

For large projects, I currently experience the refresh operation taking ~3-4min. Because the workspace is locked during this operation, this blocks other jobs such as e.g. the auto-build.

For the user, it seems like nothing is going on, even though there is a huge job blocking the application. It would be great if there is some way to visualize this operation.

![image](https://github.com/eclipse-platform/eclipse.platform/assets/70652978/73323df4-b00d-43b9-aa4a-f6ff0923f234)

To reproduce: Create a workspace with ~200000 (not a typo) files and trigger the refresh job.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
i suggest to disable automatic refresh 
![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/601b5b9e-760a-4aee-a200-f9346299d8a5)
it's only useful if you often update files from outside IDE

**Comment by ptziegler** [comment]
>  it's only useful if you often update files from outside IDE

Hm... that should work. The usual workflow is to do an initial checkout via SVN and create any additional files via the wizards. I think it's reasonable to require an explicit refresh, rather than doing it automatically in the background.
I'll give it a go and see how it goes.

Thank you for your suggestion!
There's a good chance this'll fix the problem, so I'll close this issue for now.

**Comment by laeubi** [comment]
Something similar happens when one refresh the git view I think and if one press F5 on a "high level", soI think either a job should be used, or the refresh being split into smaller chucks, e.g. only refresh a few hundred of items then release the workspace lock to allow other actions happen...
