### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by mrhempman69** [eclipse-platform/eclipse.platform#955]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

Design software development tools that are backwards compatible with existing repositories which rely on that software. 

I am pretty sure none of the developers here have heard of backwards compatibility. Basically, backwards compatibility is a term used to describe the ability of a newer version of a software, hardware, or technology to work with older versions of the same system, or with input designed for such a system.

## Community

Here is an issue comment describing two pieces of software that were broken by sloppy eclipse updates: ESP-IDF (for esp32 chips) and Bouffalo-SDK (for bl616/bl618 chips): https://github.com/espressif/idf-eclipse-plugin/issues/864#issuecomment-1845722612

**Comment by akurtakov** [comment]
@mrhempman69 I would start with the fact that the language you use would not win you any sympathy nor will it make anyone looking into issues as we obviously would better spend our time reading and hearing about "backwards compatibility" .  
I am sure that the plethora of incoming patches from you will teach us the illiterates!
Now, please go and insult another project and group of developers as the issue you point to is not coming from this project but from https://github.com/eclipse-cdt/cdt (https://github.com/eclipse-cdt/cdt/tree/main/tools.templates/org.eclipse.tools.templates.core/src/org/eclipse/tools/templates/core). Looking that the code hasn't been touched in 4 years maybe someone else has to read and research things.
