### ISSUE TITLE
PHP web debugging running prompts an internal error

### ISSUE THREAD

**Issue by lyh061619** [eclipse-platform/eclipse.platform#970]
## Problem description
Using the built-in PHP build in Server debugging mode, the following exception prompt pops up when running:
![e1](https://github.com/eclipse-platform/eclipse.platform/assets/15118571/6fb3ebb1-7259-4ccb-8c4b-dd13a60a57b3)

Exception stack:
!ENTRY org.eclipse.core.jobs 4 2 2023-12-09 09:36:15.063
!MESSAGE An internal error occurred during: "Creating console for D:\xampp\php\php.exe (Dec 9, 2023, 9:36:15 AM)".
!STACK 0
java.lang.ClassCastException: class org.eclipse.debug.core.model.RuntimeProcess cannot be cast to class org.eclipse.php.internal.debug.core.launching.PHPProcess (org.eclipse.debug.core.model.RuntimeProcess is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1a2e0676; org.eclipse.php.internal.debug.core.launching.PHPProcess is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @18ca4fe6)
	at org.eclipse.php.internal.debug.ui.console.PHPLineTracker.init(PHPLineTracker.java:47)
	at org.eclipse.debug.internal.ui.views.console.ConsoleLineNotifier.connect(ConsoleLineNotifier.java:55)
	at org.eclipse.ui.internal.console.ConsolePatternMatcher.addPatternMatchListener(ConsolePatternMatcher.java:232)
	at org.eclipse.ui.console.TextConsole.addPatternMatchListener(TextConsole.java:454)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.<init>(ProcessConsole.java:260)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsoleManager$ConsoleCreation.run(ProcessConsoleManager.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.wst.server.core 4 0 2023-12-09 09:36:15.184
!MESSAGE Server PHP Built-in Server at localhost failed to start.

## Operating environment
OS ： windows 10
JDK： zulu21.28.85-ca-jdk21.0.0
PHP： php-7.4.33 
IDE ： Version: 2023-12 (4.30.0)  Build id: 20231201-2043

## PHP.ini xdebug:
[Xdebug]

zend_extension = "D:\xampp\ext\php_xdebug-2.9.6-7.4-vc15-x86_64.dll"

xdebug.profiler_output_dir="D:\xampp\tmp\xdebug"
xdebug.trace_output_dir="D:\xampp\tmp\xdebug"

xdebug.profiler_append = Off
xdebug.profiler_enable = On
xdebug.profiler_enable_trigger = On
xdebug.profiler_output_name = "cache.out.%t-%s"

xdebug.auto_trace = On
xdebug.show_exception_trace = On
xdebug.remote_autostart = Off
xdebug.remote_enable = On
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.remote_port = 9001
xdebug.remote_host = "127.0.0.1"
xdebug.remote_handler = "dbgp"
xdebug.idekey = XDEBUG_ECLIPSE
xdebug.collect_vars = On
xdebug.collect_return = On
xdebug.collect_params = On
xdebugbug.max_nesting_level = 10000

**Comment by merks** [comment]
Please report the PHP issue here:

https://github.com/eclipse-pdt/pdt/issues

We can't move this issue to a different organization.
